/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_integrator_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {18, 1, 1};

/* dynamics_integrator_expl_vde_adj:(i0[12],i1[12],i2[6],i3[0])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][3] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][11] : 0;
  a03=arg[1]? arg[1][4] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a05=arg[0]? arg[0][10] : 0;
  a06=arg[1]? arg[1][5] : 0;
  a07=(a05*a06);
  a08=arg[0]? arg[0][4] : 0;
  a09=cos(a08);
  a10=(a07/a09);
  a10=(a01*a10);
  a00=sin(a00);
  a11=(a02*a06);
  a12=(a11/a09);
  a12=(a00*a12);
  a10=(a10+a12);
  a04=(a04-a10);
  a10=(a05*a03);
  a10=(a00*a10);
  a04=(a04-a10);
  a10=tan(a08);
  a12=arg[1]? arg[1][3] : 0;
  a13=(a02*a12);
  a14=(a10*a13);
  a14=(a00*a14);
  a04=(a04+a14);
  a14=(a05*a12);
  a15=(a10*a14);
  a15=(a01*a15);
  a04=(a04+a15);
  a15=arg[0]? arg[0][8] : 0;
  a16=arg[1]? arg[1][2] : 0;
  a17=(a15*a16);
  a18=(a09*a17);
  a18=(a00*a18);
  a04=(a04-a18);
  a18=arg[0]? arg[0][7] : 0;
  a19=(a18*a16);
  a20=(a09*a19);
  a20=(a01*a20);
  a04=(a04+a20);
  a20=arg[0]? arg[0][5] : 0;
  a21=cos(a20);
  a22=arg[1]? arg[1][1] : 0;
  a23=(a15*a22);
  a24=(a21*a23);
  a24=(a01*a24);
  a04=(a04-a24);
  a20=sin(a20);
  a08=sin(a08);
  a24=(a20*a08);
  a25=(a24*a23);
  a25=(a00*a25);
  a04=(a04-a25);
  a25=(a18*a22);
  a26=(a21*a25);
  a26=(a00*a26);
  a04=(a04-a26);
  a26=(a24*a25);
  a26=(a01*a26);
  a04=(a04+a26);
  a26=arg[1]? arg[1][0] : 0;
  a27=(a15*a26);
  a28=(a20*a27);
  a28=(a01*a28);
  a04=(a04+a28);
  a28=(a21*a08);
  a29=(a28*a27);
  a29=(a00*a29);
  a04=(a04-a29);
  a29=(a18*a26);
  a30=(a20*a29);
  a30=(a00*a30);
  a04=(a04+a30);
  a30=(a28*a29);
  a30=(a01*a30);
  a04=(a04+a30);
  if (res[0]!=0) res[0][3]=a04;
  a04=(a01/a09);
  a30=(a04/a09);
  a30=(a30*a11);
  a30=(a08*a30);
  a11=(a00/a09);
  a31=(a11/a09);
  a31=(a31*a07);
  a31=(a08*a31);
  a30=(a30-a31);
  a13=(a01*a13);
  a31=casadi_sq(a09);
  a13=(a13/a31);
  a30=(a30-a13);
  a14=(a00*a14);
  a14=(a14/a31);
  a30=(a30+a14);
  a17=(a01*a17);
  a17=(a08*a17);
  a30=(a30-a17);
  a17=arg[0]? arg[0][6] : 0;
  a14=(a17*a16);
  a14=(a09*a14);
  a30=(a30-a14);
  a19=(a00*a19);
  a19=(a08*a19);
  a30=(a30-a19);
  a19=(a01*a23);
  a14=(a20*a19);
  a14=(a09*a14);
  a30=(a30+a14);
  a14=(a00*a25);
  a31=(a20*a14);
  a31=(a09*a31);
  a30=(a30+a31);
  a31=(a17*a22);
  a13=(a20*a31);
  a13=(a08*a13);
  a30=(a30-a13);
  a13=(a01*a27);
  a07=(a21*a13);
  a07=(a09*a07);
  a30=(a30+a07);
  a07=(a00*a29);
  a32=(a21*a07);
  a32=(a09*a32);
  a30=(a30+a32);
  a32=(a17*a26);
  a33=(a21*a32);
  a33=(a08*a33);
  a30=(a30-a33);
  if (res[0]!=0) res[0][4]=a30;
  a23=(a00*a23);
  a23=(a20*a23);
  a19=(a08*a19);
  a19=(a21*a19);
  a23=(a23+a19);
  a25=(a01*a25);
  a25=(a20*a25);
  a23=(a23-a25);
  a14=(a08*a14);
  a14=(a21*a14);
  a23=(a23+a14);
  a31=(a09*a31);
  a31=(a21*a31);
  a23=(a23+a31);
  a27=(a00*a27);
  a27=(a21*a27);
  a23=(a23+a27);
  a13=(a08*a13);
  a13=(a20*a13);
  a23=(a23-a13);
  a29=(a01*a29);
  a29=(a21*a29);
  a23=(a23-a29);
  a07=(a08*a07);
  a07=(a20*a07);
  a23=(a23-a07);
  a32=(a09*a32);
  a32=(a20*a32);
  a23=(a23-a32);
  if (res[0]!=0) res[0][5]=a23;
  a23=arg[1]? arg[1][8] : 0;
  a32=(a05*a23);
  a07=arg[1]? arg[1][7] : 0;
  a29=(a02*a07);
  a32=(a32-a29);
  a08=(a08*a16);
  a32=(a32-a08);
  a08=(a20*a09);
  a08=(a08*a22);
  a32=(a32+a08);
  a08=(a21*a09);
  a08=(a08*a26);
  a32=(a32+a08);
  if (res[0]!=0) res[0][6]=a32;
  a32=arg[1]? arg[1][6] : 0;
  a08=(a02*a32);
  a29=arg[0]? arg[0][9] : 0;
  a13=(a29*a23);
  a08=(a08-a13);
  a13=(a09*a00);
  a13=(a13*a16);
  a08=(a08+a13);
  a13=(a24*a00);
  a27=(a21*a01);
  a13=(a13+a27);
  a13=(a13*a22);
  a08=(a08+a13);
  a13=(a28*a00);
  a27=(a20*a01);
  a13=(a13-a27);
  a13=(a13*a26);
  a08=(a08+a13);
  if (res[0]!=0) res[0][7]=a08;
  a08=(a29*a07);
  a13=(a05*a32);
  a08=(a08-a13);
  a09=(a09*a01);
  a09=(a09*a16);
  a08=(a08+a09);
  a24=(a24*a01);
  a21=(a21*a00);
  a24=(a24-a21);
  a24=(a24*a22);
  a08=(a08+a24);
  a28=(a28*a01);
  a20=(a20*a00);
  a28=(a28+a20);
  a28=(a28*a26);
  a08=(a08+a28);
  if (res[0]!=0) res[0][8]=a08;
  a08=1.9173465973495649e-01;
  a28=(a08*a02);
  a26=9.3605970251769381e+00;
  a20=arg[1]? arg[1][10] : 0;
  a26=(a26*a20);
  a20=(a28*a26);
  a24=1.0683079266315257e-01;
  a22=(a24*a05);
  a21=5.2155411096895339e+00;
  a09=arg[1]? arg[1][11] : 0;
  a21=(a21*a09);
  a09=(a22*a21);
  a20=(a20-a09);
  a09=1.1529282824931980e-01;
  a16=(a05*a21);
  a13=(a02*a26);
  a16=(a16-a13);
  a16=(a09*a16);
  a20=(a20+a16);
  a16=(a18*a23);
  a20=(a20-a16);
  a16=(a15*a07);
  a20=(a20+a16);
  a20=(a20+a12);
  if (res[0]!=0) res[0][9]=a20;
  a09=(a09*a29);
  a20=(a09*a21);
  a16=8.6735663890342618e+00;
  a13=arg[1]? arg[1][9] : 0;
  a16=(a16*a13);
  a02=(a02*a16);
  a13=(a29*a21);
  a02=(a02-a13);
  a24=(a24*a02);
  a20=(a20+a24);
  a28=(a28*a16);
  a20=(a20-a28);
  a28=(a17*a23);
  a20=(a20+a28);
  a15=(a15*a32);
  a20=(a20-a15);
  a11=(a11*a06);
  a20=(a20-a11);
  a11=(a01*a03);
  a20=(a20+a11);
  a11=(a10*a00);
  a11=(a11*a12);
  a20=(a20+a11);
  if (res[0]!=0) res[0][10]=a20;
  a22=(a22*a16);
  a09=(a09*a26);
  a22=(a22-a09);
  a29=(a29*a26);
  a05=(a05*a16);
  a29=(a29-a05);
  a08=(a08*a29);
  a22=(a22+a08);
  a17=(a17*a07);
  a22=(a22-a17);
  a18=(a18*a32);
  a22=(a22+a18);
  a04=(a04*a06);
  a22=(a22+a04);
  a00=(a00*a03);
  a22=(a22+a00);
  a10=(a10*a01);
  a10=(a10*a12);
  a22=(a22-a10);
  if (res[0]!=0) res[0][11]=a22;
  a22=1.8196779242861130e-01;
  a32=(a22*a32);
  if (res[0]!=0) res[0][12]=a32;
  a07=(a22*a07);
  if (res[0]!=0) res[0][13]=a07;
  a22=(a22*a23);
  if (res[0]!=0) res[0][14]=a22;
  if (res[0]!=0) res[0][15]=a16;
  if (res[0]!=0) res[0][16]=a26;
  if (res[0]!=0) res[0][17]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_integrator_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dynamics_integrator_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_integrator_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_integrator_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dynamics_integrator_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_integrator_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dynamics_integrator_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_integrator_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dynamics_integrator_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dynamics_integrator_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dynamics_integrator_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_integrator_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_integrator_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_integrator_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_integrator_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_integrator_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_integrator_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
