/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheel_force_allocation_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[57] = {8, 6, 0, 8, 16, 24, 32, 40, 48, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

/* wheel_force_allocation_expl_vde_forw:(i0[8],i1[8x8],i2[8x6],i3[6],i4[10])->(o0[8],o1[8x8],o2[8x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a7, a8, a9;
  a0=6.6666666666666671e+01;
  a1=arg[3]? arg[3][4] : 0;
  a2=1.4999999999999999e-02;
  a3=-9.8100000000000005e+00;
  a4=arg[4]? arg[4][1] : 0;
  a4=sin(a4);
  a3=(a3*a4);
  a2=(a2*a3);
  a3=1.1100000000000000e-01;
  a2=(a2/a3);
  a4=(a1-a2);
  a5=1.1030000000000000e-01;
  a6=1.;
  a7=(a1/a5);
  a8=casadi_sq(a7);
  a9=9.9999999999999995e-07;
  a8=(a8+a9);
  a8=sqrt(a8);
  a10=7.3216599999999998e-01;
  a11=arg[3]? arg[3][0] : 0;
  a11=(a10*a11);
  a12=(a8-a11);
  a12=(-a12);
  a12=exp(a12);
  a13=(a6+a12);
  a14=(1./a13);
  a15=(a6-a14);
  a16=(a15*a7);
  a17=1000000.;
  a1=(a17*a1);
  a1=tanh(a1);
  a18=(a11*a1);
  a18=(a18/a13);
  a16=(a16+a18);
  a19=100.;
  a20=arg[0]? arg[0][0] : 0;
  a20=(a3*a20);
  a21=arg[4]? arg[4][2] : 0;
  a22=-5.2573043795620514e-02;
  a23=arg[4]? arg[4][6] : 0;
  a22=(a22*a23);
  a23=1.9700000000000001e-01;
  a24=arg[4]? arg[4][7] : 0;
  a23=(a23*a24);
  a23=(a22-a23);
  a23=(a21+a23);
  a20=(a20-a23);
  a25=casadi_sq(a20);
  a25=(a25+a9);
  a25=sqrt(a25);
  a26=(a19*a25);
  a26=tanh(a26);
  a27=(a16*a26);
  a27=(a5*a27);
  a27=(a4-a27);
  a27=(a0*a27);
  if (res[0]!=0) res[0][0]=a27;
  a27=arg[3]? arg[3][1] : 0;
  a27=(a10*a27);
  a28=(a8-a27);
  a28=(-a28);
  a28=exp(a28);
  a29=(a6+a28);
  a30=(1./a29);
  a31=(a6-a30);
  a32=(a31*a7);
  a33=(a27*a1);
  a33=(a33/a29);
  a32=(a32+a33);
  a34=arg[0]? arg[0][1] : 0;
  a34=(a3*a34);
  a34=(a34-a23);
  a23=casadi_sq(a34);
  a23=(a23+a9);
  a23=sqrt(a23);
  a35=(a19*a23);
  a35=tanh(a35);
  a36=(a32*a35);
  a36=(a5*a36);
  a4=(a4-a36);
  a4=(a0*a4);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[3]? arg[3][5] : 0;
  a2=(a4-a2);
  a36=(a4/a5);
  a37=casadi_sq(a36);
  a37=(a37+a9);
  a37=sqrt(a37);
  a38=arg[3]? arg[3][2] : 0;
  a38=(a10*a38);
  a39=(a37-a38);
  a39=(-a39);
  a39=exp(a39);
  a40=(a6+a39);
  a41=(1./a40);
  a42=(a6-a41);
  a43=(a42*a36);
  a4=(a17*a4);
  a4=tanh(a4);
  a44=(a38*a4);
  a44=(a44/a40);
  a43=(a43+a44);
  a45=arg[0]? arg[0][2] : 0;
  a45=(a3*a45);
  a46=-1.9700000000000001e-01;
  a46=(a46*a24);
  a22=(a22-a46);
  a21=(a21+a22);
  a45=(a45-a21);
  a22=casadi_sq(a45);
  a22=(a22+a9);
  a22=sqrt(a22);
  a46=(a19*a22);
  a46=tanh(a46);
  a24=(a43*a46);
  a24=(a5*a24);
  a24=(a2-a24);
  a24=(a0*a24);
  if (res[0]!=0) res[0][2]=a24;
  a24=arg[3]? arg[3][3] : 0;
  a24=(a10*a24);
  a47=(a37-a24);
  a47=(-a47);
  a47=exp(a47);
  a48=(a6+a47);
  a49=(1./a48);
  a50=(a6-a49);
  a51=(a50*a36);
  a52=(a24*a4);
  a52=(a52/a48);
  a51=(a51+a52);
  a53=arg[0]? arg[0][3] : 0;
  a53=(a3*a53);
  a53=(a53-a21);
  a21=casadi_sq(a53);
  a21=(a21+a9);
  a21=sqrt(a21);
  a9=(a19*a21);
  a9=tanh(a9);
  a54=(a51*a9);
  a54=(a5*a54);
  a2=(a2-a54);
  a2=(a0*a2);
  if (res[0]!=0) res[0][3]=a2;
  a2=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a2;
  a2=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a2;
  a2=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][6]=a2;
  a2=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][7]=a2;
  a2=casadi_sq(a26);
  a2=(a6-a2);
  a20=(a20+a20);
  a54=arg[1]? arg[1][0] : 0;
  a54=(a3*a54);
  a54=(a20*a54);
  a25=(a25+a25);
  a54=(a54/a25);
  a54=(a19*a54);
  a54=(a2*a54);
  a54=(a16*a54);
  a54=(a5*a54);
  a54=(a0*a54);
  a54=(-a54);
  if (res[1]!=0) res[1][0]=a54;
  a54=casadi_sq(a35);
  a54=(a6-a54);
  a34=(a34+a34);
  a55=arg[1]? arg[1][1] : 0;
  a55=(a3*a55);
  a55=(a34*a55);
  a23=(a23+a23);
  a55=(a55/a23);
  a55=(a19*a55);
  a55=(a54*a55);
  a55=(a32*a55);
  a55=(a5*a55);
  a55=(a0*a55);
  a55=(-a55);
  if (res[1]!=0) res[1][1]=a55;
  a55=casadi_sq(a46);
  a55=(a6-a55);
  a45=(a45+a45);
  a56=arg[1]? arg[1][2] : 0;
  a56=(a3*a56);
  a56=(a45*a56);
  a22=(a22+a22);
  a56=(a56/a22);
  a56=(a19*a56);
  a56=(a55*a56);
  a56=(a43*a56);
  a56=(a5*a56);
  a56=(a0*a56);
  a56=(-a56);
  if (res[1]!=0) res[1][2]=a56;
  a56=casadi_sq(a9);
  a56=(a6-a56);
  a53=(a53+a53);
  a57=arg[1]? arg[1][3] : 0;
  a57=(a3*a57);
  a57=(a53*a57);
  a21=(a21+a21);
  a57=(a57/a21);
  a57=(a19*a57);
  a57=(a56*a57);
  a57=(a51*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][3]=a57;
  a57=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][4]=a57;
  a57=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][5]=a57;
  a57=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][6]=a57;
  a57=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][7]=a57;
  a57=arg[1]? arg[1][8] : 0;
  a57=(a3*a57);
  a57=(a20*a57);
  a57=(a57/a25);
  a57=(a19*a57);
  a57=(a2*a57);
  a57=(a16*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][8]=a57;
  a57=arg[1]? arg[1][9] : 0;
  a57=(a3*a57);
  a57=(a34*a57);
  a57=(a57/a23);
  a57=(a19*a57);
  a57=(a54*a57);
  a57=(a32*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][9]=a57;
  a57=arg[1]? arg[1][10] : 0;
  a57=(a3*a57);
  a57=(a45*a57);
  a57=(a57/a22);
  a57=(a19*a57);
  a57=(a55*a57);
  a57=(a43*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][10]=a57;
  a57=arg[1]? arg[1][11] : 0;
  a57=(a3*a57);
  a57=(a53*a57);
  a57=(a57/a21);
  a57=(a19*a57);
  a57=(a56*a57);
  a57=(a51*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][11]=a57;
  a57=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][12]=a57;
  a57=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][13]=a57;
  a57=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][14]=a57;
  a57=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][15]=a57;
  a57=arg[1]? arg[1][16] : 0;
  a57=(a3*a57);
  a57=(a20*a57);
  a57=(a57/a25);
  a57=(a19*a57);
  a57=(a2*a57);
  a57=(a16*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][16]=a57;
  a57=arg[1]? arg[1][17] : 0;
  a57=(a3*a57);
  a57=(a34*a57);
  a57=(a57/a23);
  a57=(a19*a57);
  a57=(a54*a57);
  a57=(a32*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][17]=a57;
  a57=arg[1]? arg[1][18] : 0;
  a57=(a3*a57);
  a57=(a45*a57);
  a57=(a57/a22);
  a57=(a19*a57);
  a57=(a55*a57);
  a57=(a43*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][18]=a57;
  a57=arg[1]? arg[1][19] : 0;
  a57=(a3*a57);
  a57=(a53*a57);
  a57=(a57/a21);
  a57=(a19*a57);
  a57=(a56*a57);
  a57=(a51*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][19]=a57;
  a57=arg[1]? arg[1][20] : 0;
  if (res[1]!=0) res[1][20]=a57;
  a57=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][21]=a57;
  a57=arg[1]? arg[1][22] : 0;
  if (res[1]!=0) res[1][22]=a57;
  a57=arg[1]? arg[1][23] : 0;
  if (res[1]!=0) res[1][23]=a57;
  a57=arg[1]? arg[1][24] : 0;
  a57=(a3*a57);
  a57=(a20*a57);
  a57=(a57/a25);
  a57=(a19*a57);
  a57=(a2*a57);
  a57=(a16*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][24]=a57;
  a57=arg[1]? arg[1][25] : 0;
  a57=(a3*a57);
  a57=(a34*a57);
  a57=(a57/a23);
  a57=(a19*a57);
  a57=(a54*a57);
  a57=(a32*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][25]=a57;
  a57=arg[1]? arg[1][26] : 0;
  a57=(a3*a57);
  a57=(a45*a57);
  a57=(a57/a22);
  a57=(a19*a57);
  a57=(a55*a57);
  a57=(a43*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][26]=a57;
  a57=arg[1]? arg[1][27] : 0;
  a57=(a3*a57);
  a57=(a53*a57);
  a57=(a57/a21);
  a57=(a19*a57);
  a57=(a56*a57);
  a57=(a51*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][27]=a57;
  a57=arg[1]? arg[1][28] : 0;
  if (res[1]!=0) res[1][28]=a57;
  a57=arg[1]? arg[1][29] : 0;
  if (res[1]!=0) res[1][29]=a57;
  a57=arg[1]? arg[1][30] : 0;
  if (res[1]!=0) res[1][30]=a57;
  a57=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][31]=a57;
  a57=arg[1]? arg[1][32] : 0;
  a57=(a3*a57);
  a57=(a20*a57);
  a57=(a57/a25);
  a57=(a19*a57);
  a57=(a2*a57);
  a57=(a16*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][32]=a57;
  a57=arg[1]? arg[1][33] : 0;
  a57=(a3*a57);
  a57=(a34*a57);
  a57=(a57/a23);
  a57=(a19*a57);
  a57=(a54*a57);
  a57=(a32*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][33]=a57;
  a57=arg[1]? arg[1][34] : 0;
  a57=(a3*a57);
  a57=(a45*a57);
  a57=(a57/a22);
  a57=(a19*a57);
  a57=(a55*a57);
  a57=(a43*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][34]=a57;
  a57=arg[1]? arg[1][35] : 0;
  a57=(a3*a57);
  a57=(a53*a57);
  a57=(a57/a21);
  a57=(a19*a57);
  a57=(a56*a57);
  a57=(a51*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][35]=a57;
  a57=arg[1]? arg[1][36] : 0;
  if (res[1]!=0) res[1][36]=a57;
  a57=arg[1]? arg[1][37] : 0;
  if (res[1]!=0) res[1][37]=a57;
  a57=arg[1]? arg[1][38] : 0;
  if (res[1]!=0) res[1][38]=a57;
  a57=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][39]=a57;
  a57=arg[1]? arg[1][40] : 0;
  a57=(a3*a57);
  a57=(a20*a57);
  a57=(a57/a25);
  a57=(a19*a57);
  a57=(a2*a57);
  a57=(a16*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][40]=a57;
  a57=arg[1]? arg[1][41] : 0;
  a57=(a3*a57);
  a57=(a34*a57);
  a57=(a57/a23);
  a57=(a19*a57);
  a57=(a54*a57);
  a57=(a32*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][41]=a57;
  a57=arg[1]? arg[1][42] : 0;
  a57=(a3*a57);
  a57=(a45*a57);
  a57=(a57/a22);
  a57=(a19*a57);
  a57=(a55*a57);
  a57=(a43*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][42]=a57;
  a57=arg[1]? arg[1][43] : 0;
  a57=(a3*a57);
  a57=(a53*a57);
  a57=(a57/a21);
  a57=(a19*a57);
  a57=(a56*a57);
  a57=(a51*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][43]=a57;
  a57=arg[1]? arg[1][44] : 0;
  if (res[1]!=0) res[1][44]=a57;
  a57=arg[1]? arg[1][45] : 0;
  if (res[1]!=0) res[1][45]=a57;
  a57=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][46]=a57;
  a57=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][47]=a57;
  a57=arg[1]? arg[1][48] : 0;
  a57=(a3*a57);
  a57=(a20*a57);
  a57=(a57/a25);
  a57=(a19*a57);
  a57=(a2*a57);
  a57=(a16*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][48]=a57;
  a57=arg[1]? arg[1][49] : 0;
  a57=(a3*a57);
  a57=(a34*a57);
  a57=(a57/a23);
  a57=(a19*a57);
  a57=(a54*a57);
  a57=(a32*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][49]=a57;
  a57=arg[1]? arg[1][50] : 0;
  a57=(a3*a57);
  a57=(a45*a57);
  a57=(a57/a22);
  a57=(a19*a57);
  a57=(a55*a57);
  a57=(a43*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][50]=a57;
  a57=arg[1]? arg[1][51] : 0;
  a57=(a3*a57);
  a57=(a53*a57);
  a57=(a57/a21);
  a57=(a19*a57);
  a57=(a56*a57);
  a57=(a51*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][51]=a57;
  a57=arg[1]? arg[1][52] : 0;
  if (res[1]!=0) res[1][52]=a57;
  a57=arg[1]? arg[1][53] : 0;
  if (res[1]!=0) res[1][53]=a57;
  a57=arg[1]? arg[1][54] : 0;
  if (res[1]!=0) res[1][54]=a57;
  a57=arg[1]? arg[1][55] : 0;
  if (res[1]!=0) res[1][55]=a57;
  a57=arg[1]? arg[1][56] : 0;
  a57=(a3*a57);
  a57=(a20*a57);
  a57=(a57/a25);
  a57=(a19*a57);
  a57=(a2*a57);
  a57=(a16*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][56]=a57;
  a57=arg[1]? arg[1][57] : 0;
  a57=(a3*a57);
  a57=(a34*a57);
  a57=(a57/a23);
  a57=(a19*a57);
  a57=(a54*a57);
  a57=(a32*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][57]=a57;
  a57=arg[1]? arg[1][58] : 0;
  a57=(a3*a57);
  a57=(a45*a57);
  a57=(a57/a22);
  a57=(a19*a57);
  a57=(a55*a57);
  a57=(a43*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][58]=a57;
  a57=arg[1]? arg[1][59] : 0;
  a57=(a3*a57);
  a57=(a53*a57);
  a57=(a57/a21);
  a57=(a19*a57);
  a57=(a56*a57);
  a57=(a51*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a57=(-a57);
  if (res[1]!=0) res[1][59]=a57;
  a57=arg[1]? arg[1][60] : 0;
  if (res[1]!=0) res[1][60]=a57;
  a57=arg[1]? arg[1][61] : 0;
  if (res[1]!=0) res[1][61]=a57;
  a57=arg[1]? arg[1][62] : 0;
  if (res[1]!=0) res[1][62]=a57;
  a57=arg[1]? arg[1][63] : 0;
  if (res[1]!=0) res[1][63]=a57;
  a14=(a14/a13);
  a57=(a10*a12);
  a58=(a14*a57);
  a58=(a7*a58);
  a59=(a10*a1);
  a60=(a59/a13);
  a18=(a18/a13);
  a57=(a18*a57);
  a60=(a60-a57);
  a58=(a58+a60);
  a58=(a26*a58);
  a58=(a5*a58);
  a58=(a0*a58);
  a60=arg[2]? arg[2][0] : 0;
  a60=(a3*a60);
  a60=(a20*a60);
  a60=(a60/a25);
  a60=(a19*a60);
  a60=(a2*a60);
  a60=(a16*a60);
  a60=(a5*a60);
  a60=(a0*a60);
  a58=(a58+a60);
  a58=(-a58);
  if (res[2]!=0) res[2][0]=a58;
  a58=arg[2]? arg[2][1] : 0;
  a58=(a3*a58);
  a58=(a34*a58);
  a58=(a58/a23);
  a58=(a19*a58);
  a58=(a54*a58);
  a58=(a32*a58);
  a58=(a5*a58);
  a58=(a0*a58);
  a58=(-a58);
  if (res[2]!=0) res[2][1]=a58;
  a58=arg[2]? arg[2][2] : 0;
  a58=(a3*a58);
  a58=(a45*a58);
  a58=(a58/a22);
  a58=(a19*a58);
  a58=(a55*a58);
  a58=(a43*a58);
  a58=(a5*a58);
  a58=(a0*a58);
  a58=(-a58);
  if (res[2]!=0) res[2][2]=a58;
  a58=arg[2]? arg[2][3] : 0;
  a58=(a3*a58);
  a58=(a53*a58);
  a58=(a58/a21);
  a58=(a19*a58);
  a58=(a56*a58);
  a58=(a51*a58);
  a58=(a5*a58);
  a58=(a0*a58);
  a58=(-a58);
  if (res[2]!=0) res[2][3]=a58;
  a58=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][4]=a58;
  a58=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][5]=a58;
  a58=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][6]=a58;
  a58=arg[2]? arg[2][7] : 0;
  if (res[2]!=0) res[2][7]=a58;
  a58=arg[2]? arg[2][8] : 0;
  a58=(a3*a58);
  a58=(a20*a58);
  a58=(a58/a25);
  a58=(a19*a58);
  a58=(a2*a58);
  a58=(a16*a58);
  a58=(a5*a58);
  a58=(a0*a58);
  a58=(-a58);
  if (res[2]!=0) res[2][8]=a58;
  a30=(a30/a29);
  a58=(a10*a28);
  a60=(a30*a58);
  a60=(a7*a60);
  a59=(a59/a29);
  a33=(a33/a29);
  a58=(a33*a58);
  a59=(a59-a58);
  a60=(a60+a59);
  a60=(a35*a60);
  a60=(a5*a60);
  a60=(a0*a60);
  a59=arg[2]? arg[2][9] : 0;
  a59=(a3*a59);
  a59=(a34*a59);
  a59=(a59/a23);
  a59=(a19*a59);
  a59=(a54*a59);
  a59=(a32*a59);
  a59=(a5*a59);
  a59=(a0*a59);
  a60=(a60+a59);
  a60=(-a60);
  if (res[2]!=0) res[2][9]=a60;
  a60=arg[2]? arg[2][10] : 0;
  a60=(a3*a60);
  a60=(a45*a60);
  a60=(a60/a22);
  a60=(a19*a60);
  a60=(a55*a60);
  a60=(a43*a60);
  a60=(a5*a60);
  a60=(a0*a60);
  a60=(-a60);
  if (res[2]!=0) res[2][10]=a60;
  a60=arg[2]? arg[2][11] : 0;
  a60=(a3*a60);
  a60=(a53*a60);
  a60=(a60/a21);
  a60=(a19*a60);
  a60=(a56*a60);
  a60=(a51*a60);
  a60=(a5*a60);
  a60=(a0*a60);
  a60=(-a60);
  if (res[2]!=0) res[2][11]=a60;
  a60=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][12]=a60;
  a60=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][13]=a60;
  a60=arg[2]? arg[2][14] : 0;
  if (res[2]!=0) res[2][14]=a60;
  a60=arg[2]? arg[2][15] : 0;
  if (res[2]!=0) res[2][15]=a60;
  a60=arg[2]? arg[2][16] : 0;
  a60=(a3*a60);
  a60=(a20*a60);
  a60=(a60/a25);
  a60=(a19*a60);
  a60=(a2*a60);
  a60=(a16*a60);
  a60=(a5*a60);
  a60=(a0*a60);
  a60=(-a60);
  if (res[2]!=0) res[2][16]=a60;
  a60=arg[2]? arg[2][17] : 0;
  a60=(a3*a60);
  a60=(a34*a60);
  a60=(a60/a23);
  a60=(a19*a60);
  a60=(a54*a60);
  a60=(a32*a60);
  a60=(a5*a60);
  a60=(a0*a60);
  a60=(-a60);
  if (res[2]!=0) res[2][17]=a60;
  a41=(a41/a40);
  a60=(a10*a39);
  a59=(a41*a60);
  a59=(a36*a59);
  a58=(a10*a4);
  a57=(a58/a40);
  a44=(a44/a40);
  a60=(a44*a60);
  a57=(a57-a60);
  a59=(a59+a57);
  a59=(a46*a59);
  a59=(a5*a59);
  a59=(a0*a59);
  a57=arg[2]? arg[2][18] : 0;
  a57=(a3*a57);
  a57=(a45*a57);
  a57=(a57/a22);
  a57=(a19*a57);
  a57=(a55*a57);
  a57=(a43*a57);
  a57=(a5*a57);
  a57=(a0*a57);
  a59=(a59+a57);
  a59=(-a59);
  if (res[2]!=0) res[2][18]=a59;
  a59=arg[2]? arg[2][19] : 0;
  a59=(a3*a59);
  a59=(a53*a59);
  a59=(a59/a21);
  a59=(a19*a59);
  a59=(a56*a59);
  a59=(a51*a59);
  a59=(a5*a59);
  a59=(a0*a59);
  a59=(-a59);
  if (res[2]!=0) res[2][19]=a59;
  a59=arg[2]? arg[2][20] : 0;
  if (res[2]!=0) res[2][20]=a59;
  a59=arg[2]? arg[2][21] : 0;
  if (res[2]!=0) res[2][21]=a59;
  a59=arg[2]? arg[2][22] : 0;
  if (res[2]!=0) res[2][22]=a59;
  a59=arg[2]? arg[2][23] : 0;
  if (res[2]!=0) res[2][23]=a59;
  a59=arg[2]? arg[2][24] : 0;
  a59=(a3*a59);
  a59=(a20*a59);
  a59=(a59/a25);
  a59=(a19*a59);
  a59=(a2*a59);
  a59=(a16*a59);
  a59=(a5*a59);
  a59=(a0*a59);
  a59=(-a59);
  if (res[2]!=0) res[2][24]=a59;
  a59=arg[2]? arg[2][25] : 0;
  a59=(a3*a59);
  a59=(a34*a59);
  a59=(a59/a23);
  a59=(a19*a59);
  a59=(a54*a59);
  a59=(a32*a59);
  a59=(a5*a59);
  a59=(a0*a59);
  a59=(-a59);
  if (res[2]!=0) res[2][25]=a59;
  a59=arg[2]? arg[2][26] : 0;
  a59=(a3*a59);
  a59=(a45*a59);
  a59=(a59/a22);
  a59=(a19*a59);
  a59=(a55*a59);
  a59=(a43*a59);
  a59=(a5*a59);
  a59=(a0*a59);
  a59=(-a59);
  if (res[2]!=0) res[2][26]=a59;
  a49=(a49/a48);
  a10=(a10*a47);
  a59=(a49*a10);
  a59=(a36*a59);
  a58=(a58/a48);
  a52=(a52/a48);
  a10=(a52*a10);
  a58=(a58-a10);
  a59=(a59+a58);
  a59=(a9*a59);
  a59=(a5*a59);
  a59=(a0*a59);
  a58=arg[2]? arg[2][27] : 0;
  a58=(a3*a58);
  a58=(a53*a58);
  a58=(a58/a21);
  a58=(a19*a58);
  a58=(a56*a58);
  a58=(a51*a58);
  a58=(a5*a58);
  a58=(a0*a58);
  a59=(a59+a58);
  a59=(-a59);
  if (res[2]!=0) res[2][27]=a59;
  a59=arg[2]? arg[2][28] : 0;
  if (res[2]!=0) res[2][28]=a59;
  a59=arg[2]? arg[2][29] : 0;
  if (res[2]!=0) res[2][29]=a59;
  a59=arg[2]? arg[2][30] : 0;
  if (res[2]!=0) res[2][30]=a59;
  a59=arg[2]? arg[2][31] : 0;
  if (res[2]!=0) res[2][31]=a59;
  a59=9.0661831368993653e+00;
  a15=(a59*a15);
  a58=(a7+a7);
  a58=(a59*a58);
  a8=(a8+a8);
  a58=(a58/a8);
  a12=(a12*a58);
  a14=(a14*a12);
  a14=(a7*a14);
  a15=(a15-a14);
  a1=casadi_sq(a1);
  a1=(a6-a1);
  a1=(a17*a1);
  a11=(a11*a1);
  a11=(a11/a13);
  a18=(a18*a12);
  a11=(a11+a18);
  a15=(a15+a11);
  a26=(a26*a15);
  a26=(a5*a26);
  a26=(a6-a26);
  a26=(a0*a26);
  a15=arg[2]? arg[2][32] : 0;
  a15=(a3*a15);
  a15=(a20*a15);
  a15=(a15/a25);
  a15=(a19*a15);
  a15=(a2*a15);
  a15=(a16*a15);
  a15=(a5*a15);
  a15=(a0*a15);
  a26=(a26-a15);
  if (res[2]!=0) res[2][32]=a26;
  a31=(a59*a31);
  a28=(a28*a58);
  a30=(a30*a28);
  a7=(a7*a30);
  a31=(a31-a7);
  a27=(a27*a1);
  a27=(a27/a29);
  a33=(a33*a28);
  a27=(a27+a33);
  a31=(a31+a27);
  a35=(a35*a31);
  a35=(a5*a35);
  a35=(a6-a35);
  a35=(a0*a35);
  a31=arg[2]? arg[2][33] : 0;
  a31=(a3*a31);
  a31=(a34*a31);
  a31=(a31/a23);
  a31=(a19*a31);
  a31=(a54*a31);
  a31=(a32*a31);
  a31=(a5*a31);
  a31=(a0*a31);
  a35=(a35-a31);
  if (res[2]!=0) res[2][33]=a35;
  a35=arg[2]? arg[2][34] : 0;
  a35=(a3*a35);
  a35=(a45*a35);
  a35=(a35/a22);
  a35=(a19*a35);
  a35=(a55*a35);
  a35=(a43*a35);
  a35=(a5*a35);
  a35=(a0*a35);
  a35=(-a35);
  if (res[2]!=0) res[2][34]=a35;
  a35=arg[2]? arg[2][35] : 0;
  a35=(a3*a35);
  a35=(a53*a35);
  a35=(a35/a21);
  a35=(a19*a35);
  a35=(a56*a35);
  a35=(a51*a35);
  a35=(a5*a35);
  a35=(a0*a35);
  a35=(-a35);
  if (res[2]!=0) res[2][35]=a35;
  a35=arg[2]? arg[2][36] : 0;
  if (res[2]!=0) res[2][36]=a35;
  a35=arg[2]? arg[2][37] : 0;
  if (res[2]!=0) res[2][37]=a35;
  a35=arg[2]? arg[2][38] : 0;
  if (res[2]!=0) res[2][38]=a35;
  a35=arg[2]? arg[2][39] : 0;
  if (res[2]!=0) res[2][39]=a35;
  a35=arg[2]? arg[2][40] : 0;
  a35=(a3*a35);
  a20=(a20*a35);
  a20=(a20/a25);
  a20=(a19*a20);
  a2=(a2*a20);
  a16=(a16*a2);
  a16=(a5*a16);
  a16=(a0*a16);
  a16=(-a16);
  if (res[2]!=0) res[2][40]=a16;
  a16=arg[2]? arg[2][41] : 0;
  a16=(a3*a16);
  a34=(a34*a16);
  a34=(a34/a23);
  a34=(a19*a34);
  a54=(a54*a34);
  a32=(a32*a54);
  a32=(a5*a32);
  a32=(a0*a32);
  a32=(-a32);
  if (res[2]!=0) res[2][41]=a32;
  a42=(a59*a42);
  a32=(a36+a36);
  a32=(a59*a32);
  a37=(a37+a37);
  a32=(a32/a37);
  a39=(a39*a32);
  a41=(a41*a39);
  a41=(a36*a41);
  a42=(a42-a41);
  a4=casadi_sq(a4);
  a4=(a6-a4);
  a17=(a17*a4);
  a38=(a38*a17);
  a38=(a38/a40);
  a44=(a44*a39);
  a38=(a38+a44);
  a42=(a42+a38);
  a46=(a46*a42);
  a46=(a5*a46);
  a46=(a6-a46);
  a46=(a0*a46);
  a42=arg[2]? arg[2][42] : 0;
  a42=(a3*a42);
  a45=(a45*a42);
  a45=(a45/a22);
  a45=(a19*a45);
  a55=(a55*a45);
  a43=(a43*a55);
  a43=(a5*a43);
  a43=(a0*a43);
  a46=(a46-a43);
  if (res[2]!=0) res[2][42]=a46;
  a59=(a59*a50);
  a47=(a47*a32);
  a49=(a49*a47);
  a36=(a36*a49);
  a59=(a59-a36);
  a24=(a24*a17);
  a24=(a24/a48);
  a52=(a52*a47);
  a24=(a24+a52);
  a59=(a59+a24);
  a9=(a9*a59);
  a9=(a5*a9);
  a6=(a6-a9);
  a6=(a0*a6);
  a9=arg[2]? arg[2][43] : 0;
  a3=(a3*a9);
  a53=(a53*a3);
  a53=(a53/a21);
  a19=(a19*a53);
  a56=(a56*a19);
  a51=(a51*a56);
  a5=(a5*a51);
  a0=(a0*a5);
  a6=(a6-a0);
  if (res[2]!=0) res[2][43]=a6;
  a6=arg[2]? arg[2][44] : 0;
  if (res[2]!=0) res[2][44]=a6;
  a6=arg[2]? arg[2][45] : 0;
  if (res[2]!=0) res[2][45]=a6;
  a6=arg[2]? arg[2][46] : 0;
  if (res[2]!=0) res[2][46]=a6;
  a6=arg[2]? arg[2][47] : 0;
  if (res[2]!=0) res[2][47]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheel_force_allocation_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int wheel_force_allocation_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real wheel_force_allocation_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheel_force_allocation_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheel_force_allocation_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheel_force_allocation_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheel_force_allocation_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
