/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {2, 1, 1};
static const casadi_int casadi_s3[3] = {6, 1, 1};
static const casadi_int casadi_s4[10] = 
  {9, 2, 0, 3, 5, 2, 3, 7,
  0, 1};
static const casadi_int casadi_s5[21] = 
  {9, 9, 0, 1, 2, 4, 7, 7,
  7, 7, 9, 9, 0, 1, 2, 3,
  2, 3, 7, 3, 7};
static const casadi_int casadi_s6[3] = {2, 0, 1};
static const casadi_int casadi_s7[3] = {0, 0, 1};

/* dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess:(i0[9],i1[0],i2[2],i3[0],i4[6])->(o0[2],o1[9x2,5nz],o2[9x9,9nz],o3[2x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18;
  a00=-5.3910639180000004e+01;
  a01=arg[0]? arg[0][3] : 0;
  a02=sin(a01);
  a03=(a00*a02);
  a04=4.;
  a03=(a03/a04);
  a05=arg[0]? arg[0][7] : 0;
  a03=(a03+a05);
  a05=casadi_sq(a03);
  a06=5.3910639180000004e+01;
  a01=cos(a01);
  a07=(a06*a01);
  a08=arg[0]? arg[0][2] : 0;
  a09=sin(a08);
  a10=(a07*a09);
  a10=(a10/a04);
  a11=casadi_sq(a10);
  a05=(a05+a11);
  a11=-9.8100000000000005e+00;
  a12=5.4954780000000003e+00;
  a13=arg[4]? arg[4][0] : 0;
  a12=(a12*a13);
  a11=(a11*a12);
  a12=(a11*a01);
  a08=cos(a08);
  a13=(a12*a08);
  a13=(a13/a04);
  a04=casadi_sq(a13);
  a05=(a05-a04);
  if (res[0]!=0) res[0][0]=a05;
  a05=arg[0]? arg[0][0] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a05=(a05-a04);
  a04=casadi_sq(a05);
  a14=arg[0]? arg[0][1] : 0;
  a15=arg[4]? arg[4][3] : 0;
  a14=(a14-a15);
  a15=casadi_sq(a14);
  a04=(a04+a15);
  a15=arg[4]? arg[4][4] : 0;
  a16=arg[4]? arg[4][5] : 0;
  a15=(a15-a16);
  a15=casadi_sq(a15);
  a04=(a04-a15);
  if (res[0]!=0) res[0][1]=a04;
  a04=2.5000000000000000e-01;
  a13=(a13+a13);
  a15=(a04*a13);
  a16=(a12*a15);
  a16=(a09*a16);
  a10=(a10+a10);
  a17=(a04*a10);
  a18=(a07*a17);
  a18=(a08*a18);
  a16=(a16+a18);
  if (res[1]!=0) res[1][0]=a16;
  a15=(a08*a15);
  a15=(a11*a15);
  a15=(a02*a15);
  a17=(a09*a17);
  a17=(a06*a17);
  a17=(a02*a17);
  a15=(a15-a17);
  a03=(a03+a03);
  a17=(a04*a03);
  a17=(a00*a17);
  a17=(a01*a17);
  a15=(a15+a17);
  if (res[1]!=0) res[1][1]=a15;
  if (res[1]!=0) res[1][2]=a03;
  a05=(a05+a05);
  if (res[1]!=0) res[1][3]=a05;
  a14=(a14+a14);
  if (res[1]!=0) res[1][4]=a14;
  a14=2.;
  a05=arg[2]? arg[2][1] : 0;
  a05=(a14*a05);
  if (res[2]!=0) res[2][0]=a05;
  if (res[2]!=0) res[2][1]=a05;
  a05=arg[2]? arg[2][0] : 0;
  a13=(a13*a05);
  a13=(a04*a13);
  a15=(a12*a13);
  a15=(a15*a08);
  a17=(a12*a09);
  a17=(a04*a17);
  a17=(a17+a17);
  a17=(a05*a17);
  a17=(a04*a17);
  a17=(a12*a17);
  a17=(a09*a17);
  a15=(a15-a17);
  a17=(a07*a08);
  a17=(a04*a17);
  a17=(a17+a17);
  a17=(a05*a17);
  a17=(a04*a17);
  a17=(a07*a17);
  a17=(a08*a17);
  a10=(a10*a05);
  a10=(a04*a10);
  a16=(a07*a10);
  a16=(a16*a09);
  a17=(a17-a16);
  a15=(a15+a17);
  if (res[2]!=0) res[2][2]=a15;
  a15=(a11*a02);
  a17=(a13*a15);
  a15=(a08*a15);
  a15=(a04*a15);
  a15=(a15+a15);
  a15=(a05*a15);
  a15=(a04*a15);
  a12=(a12*a15);
  a17=(a17+a12);
  a17=(a09*a17);
  a12=(a06*a02);
  a16=(a10*a12);
  a12=(a09*a12);
  a12=(a04*a12);
  a12=(a12+a12);
  a12=(a05*a12);
  a12=(a04*a12);
  a07=(a07*a12);
  a16=(a16+a07);
  a16=(a08*a16);
  a17=(a17+a16);
  a17=(-a17);
  if (res[2]!=0) res[2][3]=a17;
  if (res[2]!=0) res[2][4]=a17;
  a13=(a08*a13);
  a13=(a11*a13);
  a13=(a13*a01);
  a08=(a08*a15);
  a11=(a11*a08);
  a11=(a02*a11);
  a13=(a13-a11);
  a10=(a09*a10);
  a10=(a06*a10);
  a10=(a10*a01);
  a09=(a09*a12);
  a06=(a06*a09);
  a06=(a02*a06);
  a10=(a10-a06);
  a13=(a13-a10);
  a10=(a00*a01);
  a10=(a04*a10);
  a10=(a10+a10);
  a10=(a05*a10);
  a06=(a04*a10);
  a06=(a00*a06);
  a01=(a01*a06);
  a03=(a03*a05);
  a04=(a04*a03);
  a00=(a00*a04);
  a00=(a00*a02);
  a01=(a01-a00);
  a13=(a13+a01);
  if (res[2]!=0) res[2][5]=a13;
  if (res[2]!=0) res[2][6]=a10;
  if (res[2]!=0) res[2][7]=a10;
  a14=(a14*a05);
  if (res[2]!=0) res[2][8]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s1;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_constr_h_e_fun_jac_uxt_zt_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
