/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheel_force_allocation_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

/* wheel_force_allocation_cost_ext_cost_fun_jac:(i0[8],i1[6],i2[0],i3[10])->(o0,o1[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a9;
  a0=arg[0]? arg[0][4] : 0;
  a1=casadi_sq(a0);
  a2=arg[0]? arg[0][5] : 0;
  a3=casadi_sq(a2);
  a1=(a1+a3);
  a3=arg[0]? arg[0][6] : 0;
  a4=casadi_sq(a3);
  a1=(a1+a4);
  a4=arg[0]? arg[0][7] : 0;
  a5=casadi_sq(a4);
  a1=(a1+a5);
  a5=2.;
  a6=1.;
  a7=arg[1]? arg[1][4] : 0;
  a8=1.1030000000000000e-01;
  a9=(a7/a8);
  a10=casadi_sq(a9);
  a11=9.9999999999999995e-07;
  a10=(a10+a11);
  a10=sqrt(a10);
  a12=7.3216599999999998e-01;
  a13=arg[1]? arg[1][0] : 0;
  a14=(a12*a13);
  a15=(a10-a14);
  a15=(-a15);
  a15=exp(a15);
  a16=(a6+a15);
  a17=(1./a16);
  a18=(a6-a17);
  a19=(a18*a9);
  a20=1000000.;
  a21=(a20*a7);
  a21=tanh(a21);
  a22=(a14*a21);
  a22=(a22/a16);
  a19=(a19+a22);
  a23=100.;
  a24=1.1100000000000000e-01;
  a25=arg[0]? arg[0][0] : 0;
  a25=(a24*a25);
  a26=arg[3]? arg[3][2] : 0;
  a27=-5.2573043795620514e-02;
  a28=arg[3]? arg[3][6] : 0;
  a28=(a27*a28);
  a29=1.9700000000000001e-01;
  a30=arg[3]? arg[3][7] : 0;
  a31=(a29*a30);
  a31=(a28-a31);
  a31=(a26+a31);
  a25=(a25-a31);
  a32=casadi_sq(a25);
  a32=(a32+a11);
  a32=sqrt(a32);
  a33=(a23*a32);
  a33=tanh(a33);
  a34=(a19*a33);
  a35=2.7399999999999999e+01;
  a36=-9.8100000000000005e+00;
  a37=arg[3]? arg[3][1] : 0;
  a38=sin(a37);
  a38=(a36*a38);
  a38=(a35*a38);
  a38=(a34-a38);
  a39=arg[1]? arg[1][1] : 0;
  a40=(a12*a39);
  a41=(a10-a40);
  a41=(-a41);
  a41=exp(a41);
  a42=(a6+a41);
  a43=(1./a42);
  a44=(a6-a43);
  a45=(a44*a9);
  a46=(a40*a21);
  a46=(a46/a42);
  a45=(a45+a46);
  a47=arg[0]? arg[0][1] : 0;
  a47=(a24*a47);
  a47=(a47-a31);
  a31=casadi_sq(a47);
  a31=(a31+a11);
  a31=sqrt(a31);
  a48=(a23*a31);
  a48=tanh(a48);
  a49=(a45*a48);
  a38=(a38+a49);
  a50=arg[1]? arg[1][5] : 0;
  a8=(a50/a8);
  a51=casadi_sq(a8);
  a51=(a51+a11);
  a51=sqrt(a51);
  a52=arg[1]? arg[1][2] : 0;
  a53=(a12*a52);
  a54=(a51-a53);
  a54=(-a54);
  a54=exp(a54);
  a55=(a6+a54);
  a56=(1./a55);
  a57=(a6-a56);
  a58=(a57*a8);
  a59=(a20*a50);
  a59=tanh(a59);
  a60=(a53*a59);
  a60=(a60/a55);
  a58=(a58+a60);
  a61=arg[0]? arg[0][2] : 0;
  a61=(a24*a61);
  a62=-1.9700000000000001e-01;
  a63=(a62*a30);
  a28=(a28-a63);
  a26=(a26+a28);
  a61=(a61-a26);
  a28=casadi_sq(a61);
  a28=(a28+a11);
  a28=sqrt(a28);
  a63=(a23*a28);
  a63=tanh(a63);
  a64=(a58*a63);
  a38=(a38+a64);
  a65=arg[1]? arg[1][3] : 0;
  a66=(a12*a65);
  a67=(a51-a66);
  a67=(-a67);
  a67=exp(a67);
  a68=(a6+a67);
  a69=(1./a68);
  a70=(a6-a69);
  a71=(a70*a8);
  a72=(a66*a59);
  a72=(a72/a68);
  a71=(a71+a72);
  a73=arg[0]? arg[0][3] : 0;
  a73=(a24*a73);
  a73=(a73-a26);
  a26=casadi_sq(a73);
  a26=(a26+a11);
  a26=sqrt(a26);
  a11=(a23*a26);
  a11=tanh(a11);
  a74=(a71*a11);
  a38=(a38+a74);
  a75=arg[3]? arg[3][8] : 0;
  a38=(a38-a75);
  a75=(a5*a38);
  a38=(a75*a38);
  a1=(a1+a38);
  a37=cos(a37);
  a38=arg[3]? arg[3][0] : 0;
  a76=sin(a38);
  a76=(a37*a76);
  a76=(a36*a76);
  a76=(a35*a76);
  a77=-7.3216599999999998e-01;
  a78=(a77*a13);
  a79=arg[3]? arg[3][3] : 0;
  a80=-1.3404387591240877e-01;
  a81=(a80*a30);
  a82=arg[3]? arg[3][5] : 0;
  a27=(a27*a82);
  a81=(a81-a27);
  a81=(a79+a81);
  a81=(a23*a81);
  a81=tanh(a81);
  a78=(a78*a81);
  a76=(a76+a78);
  a82=(a77*a39);
  a83=1.3495612408759125e-01;
  a30=(a83*a30);
  a30=(a30-a27);
  a79=(a79+a30);
  a79=(a23*a79);
  a79=tanh(a79);
  a82=(a82*a79);
  a76=(a76+a82);
  a30=(a77*a52);
  a30=(a30*a81);
  a76=(a76+a30);
  a27=(a77*a65);
  a27=(a27*a79);
  a76=(a76+a27);
  a84=(a5*a76);
  a76=(a84*a76);
  a1=(a1+a76);
  a38=cos(a38);
  a37=(a37*a38);
  a36=(a36*a37);
  a35=(a35*a36);
  a35=(a35+a13);
  a35=(a35+a39);
  a35=(a35+a52);
  a35=(a35+a65);
  a65=(a5*a35);
  a35=(a65*a35);
  a1=(a1+a35);
  a34=(a62*a34);
  a78=(a80*a78);
  a34=(a34+a78);
  a49=(a62*a49);
  a82=(a83*a82);
  a49=(a49+a82);
  a34=(a34+a49);
  a64=(a29*a64);
  a30=(a80*a30);
  a64=(a64+a30);
  a34=(a34+a64);
  a74=(a29*a74);
  a27=(a83*a27);
  a74=(a74+a27);
  a34=(a34+a74);
  a74=arg[3]? arg[3][9] : 0;
  a34=(a34-a74);
  a5=(a5*a34);
  a34=(a5*a34);
  a1=(a1+a34);
  a34=10.;
  a74=(a34*a7);
  a7=(a74*a7);
  a1=(a1+a7);
  a34=(a34*a50);
  a50=(a34*a50);
  a1=(a1+a50);
  if (res[0]!=0) res[0][0]=a1;
  a65=(a65+a65);
  a5=(a5+a5);
  a80=(a80*a5);
  a84=(a84+a84);
  a80=(a80+a84);
  a81=(a81*a80);
  a81=(a77*a81);
  a81=(a65+a81);
  a62=(a62*a5);
  a75=(a75+a75);
  a62=(a62+a75);
  a80=(a33*a62);
  a1=(a80/a16);
  a50=(a21*a1);
  a50=(a12*a50);
  a50=(a81+a50);
  a17=(a17/a16);
  a7=(a9*a80);
  a17=(a17*a7);
  a22=(a22/a16);
  a22=(a22*a80);
  a17=(a17-a22);
  a15=(a15*a17);
  a17=(a12*a15);
  a50=(a50+a17);
  if (res[1]!=0) res[1][0]=a50;
  a83=(a83*a5);
  a83=(a83+a84);
  a79=(a79*a83);
  a77=(a77*a79);
  a65=(a65+a77);
  a77=(a48*a62);
  a79=(a77/a42);
  a83=(a21*a79);
  a83=(a12*a83);
  a83=(a65+a83);
  a43=(a43/a42);
  a84=(a9*a77);
  a43=(a43*a84);
  a46=(a46/a42);
  a46=(a46*a77);
  a43=(a43-a46);
  a41=(a41*a43);
  a43=(a12*a41);
  a83=(a83+a43);
  if (res[1]!=0) res[1][1]=a83;
  a29=(a29*a5);
  a29=(a29+a75);
  a75=(a63*a29);
  a5=(a75/a55);
  a83=(a59*a5);
  a83=(a12*a83);
  a81=(a81+a83);
  a56=(a56/a55);
  a83=(a8*a75);
  a56=(a56*a83);
  a60=(a60/a55);
  a60=(a60*a75);
  a56=(a56-a60);
  a54=(a54*a56);
  a56=(a12*a54);
  a81=(a81+a56);
  if (res[1]!=0) res[1][2]=a81;
  a81=(a11*a29);
  a56=(a81/a68);
  a60=(a59*a56);
  a60=(a12*a60);
  a65=(a65+a60);
  a69=(a69/a68);
  a60=(a8*a81);
  a69=(a69*a60);
  a72=(a72/a68);
  a72=(a72*a81);
  a69=(a69-a72);
  a67=(a67*a69);
  a12=(a12*a67);
  a65=(a65+a12);
  if (res[1]!=0) res[1][3]=a65;
  a74=(a74+a74);
  a21=casadi_sq(a21);
  a21=(a6-a21);
  a40=(a40*a79);
  a40=(a21*a40);
  a40=(a20*a40);
  a74=(a74+a40);
  a40=9.0661831368993653e+00;
  a44=(a44*a77);
  a44=(a40*a44);
  a74=(a74+a44);
  a9=(a9+a9);
  a10=(a10+a10);
  a41=(a41/a10);
  a41=(a9*a41);
  a41=(a40*a41);
  a74=(a74-a41);
  a14=(a14*a1);
  a21=(a21*a14);
  a21=(a20*a21);
  a74=(a74+a21);
  a18=(a18*a80);
  a18=(a40*a18);
  a74=(a74+a18);
  a15=(a15/a10);
  a9=(a9*a15);
  a9=(a40*a9);
  a74=(a74-a9);
  if (res[1]!=0) res[1][4]=a74;
  a34=(a34+a34);
  a59=casadi_sq(a59);
  a59=(a6-a59);
  a66=(a66*a56);
  a66=(a59*a66);
  a66=(a20*a66);
  a34=(a34+a66);
  a70=(a70*a81);
  a70=(a40*a70);
  a34=(a34+a70);
  a8=(a8+a8);
  a51=(a51+a51);
  a67=(a67/a51);
  a67=(a8*a67);
  a67=(a40*a67);
  a34=(a34-a67);
  a53=(a53*a5);
  a59=(a59*a53);
  a20=(a20*a59);
  a34=(a34+a20);
  a57=(a57*a75);
  a57=(a40*a57);
  a34=(a34+a57);
  a54=(a54/a51);
  a8=(a8*a54);
  a40=(a40*a8);
  a34=(a34-a40);
  if (res[1]!=0) res[1][5]=a34;
  a25=(a25+a25);
  a33=casadi_sq(a33);
  a33=(a6-a33);
  a19=(a19*a62);
  a33=(a33*a19);
  a33=(a23*a33);
  a32=(a32+a32);
  a33=(a33/a32);
  a25=(a25*a33);
  a25=(a24*a25);
  if (res[1]!=0) res[1][6]=a25;
  a47=(a47+a47);
  a48=casadi_sq(a48);
  a48=(a6-a48);
  a45=(a45*a62);
  a48=(a48*a45);
  a48=(a23*a48);
  a31=(a31+a31);
  a48=(a48/a31);
  a47=(a47*a48);
  a47=(a24*a47);
  if (res[1]!=0) res[1][7]=a47;
  a61=(a61+a61);
  a63=casadi_sq(a63);
  a63=(a6-a63);
  a58=(a58*a29);
  a63=(a63*a58);
  a63=(a23*a63);
  a28=(a28+a28);
  a63=(a63/a28);
  a61=(a61*a63);
  a61=(a24*a61);
  if (res[1]!=0) res[1][8]=a61;
  a73=(a73+a73);
  a11=casadi_sq(a11);
  a6=(a6-a11);
  a71=(a71*a29);
  a6=(a6*a71);
  a23=(a23*a6);
  a26=(a26+a26);
  a23=(a23/a26);
  a73=(a73*a23);
  a24=(a24*a73);
  if (res[1]!=0) res[1][9]=a24;
  a0=(a0+a0);
  if (res[1]!=0) res[1][10]=a0;
  a2=(a2+a2);
  if (res[1]!=0) res[1][11]=a2;
  a3=(a3+a3);
  if (res[1]!=0) res[1][12]=a3;
  a4=(a4+a4);
  if (res[1]!=0) res[1][13]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheel_force_allocation_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int wheel_force_allocation_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real wheel_force_allocation_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheel_force_allocation_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheel_force_allocation_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheel_force_allocation_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheel_force_allocation_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
