/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheel_force_allocation_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* wheel_force_allocation_cost_ext_cost_fun:(i0[4],i1[6],i2[0],i3[10])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=2.;
  a1=7.3216599999999998e-01;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1*a2);
  a4=100.;
  a5=1.1100000000000000e-01;
  a6=arg[0]? arg[0][0] : 0;
  a6=(a5*a6);
  a7=arg[3]? arg[3][2] : 0;
  a8=-5.2573043795620514e-02;
  a9=arg[3]? arg[3][6] : 0;
  a8=(a8*a9);
  a9=1.9700000000000001e-01;
  a10=arg[3]? arg[3][7] : 0;
  a11=(a9*a10);
  a11=(a8-a11);
  a11=(a7+a11);
  a6=(a6-a11);
  a6=(a4*a6);
  a6=tanh(a6);
  a3=(a3*a6);
  a6=2.7399999999999999e+01;
  a12=-9.8100000000000005e+00;
  a13=arg[3]? arg[3][1] : 0;
  a14=sin(a13);
  a14=(a12*a14);
  a14=(a6*a14);
  a14=(a3-a14);
  a15=arg[1]? arg[1][1] : 0;
  a16=(a1*a15);
  a17=arg[0]? arg[0][1] : 0;
  a17=(a5*a17);
  a17=(a17-a11);
  a17=(a4*a17);
  a17=tanh(a17);
  a16=(a16*a17);
  a14=(a14+a16);
  a17=arg[1]? arg[1][2] : 0;
  a11=(a1*a17);
  a18=arg[0]? arg[0][2] : 0;
  a18=(a5*a18);
  a19=-1.9700000000000001e-01;
  a10=(a19*a10);
  a8=(a8-a10);
  a7=(a7+a8);
  a18=(a18-a7);
  a18=(a4*a18);
  a18=tanh(a18);
  a11=(a11*a18);
  a14=(a14+a11);
  a18=arg[1]? arg[1][3] : 0;
  a1=(a1*a18);
  a8=arg[0]? arg[0][3] : 0;
  a5=(a5*a8);
  a5=(a5-a7);
  a4=(a4*a5);
  a4=tanh(a4);
  a1=(a1*a4);
  a14=(a14+a1);
  a4=arg[3]? arg[3][8] : 0;
  a14=(a14-a4);
  a4=(a0*a14);
  a4=(a4*a14);
  a13=cos(a13);
  a14=arg[3]? arg[3][0] : 0;
  a5=sin(a14);
  a5=(a13*a5);
  a5=(a12*a5);
  a5=(a6*a5);
  a7=(a0*a5);
  a7=(a7*a5);
  a4=(a4+a7);
  a14=cos(a14);
  a13=(a13*a14);
  a12=(a12*a13);
  a6=(a6*a12);
  a6=(a6+a2);
  a6=(a6+a15);
  a6=(a6+a17);
  a6=(a6+a18);
  a18=(a0*a6);
  a18=(a18*a6);
  a4=(a4+a18);
  a3=(a19*a3);
  a19=(a19*a16);
  a3=(a3+a19);
  a11=(a9*a11);
  a3=(a3+a11);
  a9=(a9*a1);
  a3=(a3+a9);
  a9=arg[3]? arg[3][9] : 0;
  a3=(a3-a9);
  a0=(a0*a3);
  a0=(a0*a3);
  a4=(a4+a0);
  a0=10.;
  a3=arg[1]? arg[1][4] : 0;
  a9=(a0*a3);
  a9=(a9*a3);
  a4=(a4+a9);
  a9=arg[1]? arg[1][5] : 0;
  a0=(a0*a9);
  a0=(a0*a9);
  a4=(a4+a0);
  if (res[0]!=0) res[0][0]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheel_force_allocation_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheel_force_allocation_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int wheel_force_allocation_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wheel_force_allocation_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheel_force_allocation_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheel_force_allocation_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheel_force_allocation_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheel_force_allocation_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheel_force_allocation_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
