/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_rates_path_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {9, 9, 1};
static const casadi_int casadi_s2[3] = {9, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};

/* dynamics_rates_path_expl_vde_forw:(i0[9],i1[9x9],i2[9x2],i3[2],i4[2])->(o0[9],o1[9x9],o2[9x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=arg[0]? arg[0][3] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][4] : 0;
  a03=cos(a02);
  a04=(a01*a03);
  a05=arg[0]? arg[0][5] : 0;
  a06=(a04*a05);
  if (res[0]!=0) res[0][0]=a06;
  a02=sin(a02);
  a06=(a01*a02);
  a07=(a06*a05);
  if (res[0]!=0) res[0][1]=a07;
  a07=tan(a00);
  a08=arg[0]? arg[0][2] : 0;
  a09=cos(a08);
  a10=(a07*a09);
  a11=arg[0]? arg[0][6] : 0;
  a12=(a10*a11);
  a12=(-a12);
  if (res[0]!=0) res[0][2]=a12;
  a08=sin(a08);
  a12=(a08*a11);
  if (res[0]!=0) res[0][3]=a12;
  a12=(a09/a01);
  a13=(a12*a11);
  if (res[0]!=0) res[0][4]=a13;
  a13=2.;
  a14=-5.3910639180000004e+01;
  a00=sin(a00);
  a15=(a14*a00);
  a16=4.;
  a15=(a15/a16);
  a16=arg[0]? arg[0][7] : 0;
  a16=(a15+a16);
  a17=arg[0]? arg[0][8] : 0;
  a15=(a15+a17);
  a17=(a16+a15);
  a17=(a13*a17);
  a18=5.4954780000000003e+00;
  a17=(a17/a18);
  a18=-9.8100000000000005e+00;
  a19=(a18*a00);
  a17=(a17-a19);
  if (res[0]!=0) res[0][5]=a17;
  a17=4.4800000000000001e-01;
  a15=(a15-a16);
  a15=(a17*a15);
  a16=1.9173465973495649e-01;
  a15=(a15/a16);
  if (res[0]!=0) res[0][6]=a15;
  a15=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][7]=a15;
  a15=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][8]=a15;
  a15=arg[1]? arg[1][5] : 0;
  a16=(a04*a15);
  a19=arg[1]? arg[1][3] : 0;
  a20=(a00*a19);
  a21=(a03*a20);
  a22=arg[1]? arg[1][4] : 0;
  a23=(a02*a22);
  a23=(a01*a23);
  a21=(a21+a23);
  a21=(a05*a21);
  a16=(a16-a21);
  if (res[1]!=0) res[1][0]=a16;
  a22=(a03*a22);
  a22=(a01*a22);
  a16=(a02*a20);
  a22=(a22-a16);
  a22=(a05*a22);
  a15=(a06*a15);
  a22=(a22+a15);
  if (res[1]!=0) res[1][1]=a22;
  a22=casadi_sq(a01);
  a15=(a19/a22);
  a15=(a09*a15);
  a16=arg[1]? arg[1][2] : 0;
  a21=(a08*a16);
  a23=(a07*a21);
  a15=(a15-a23);
  a15=(a11*a15);
  a23=arg[1]? arg[1][6] : 0;
  a24=(a10*a23);
  a15=(a15+a24);
  a15=(-a15);
  if (res[1]!=0) res[1][2]=a15;
  a16=(a09*a16);
  a16=(a11*a16);
  a15=(a08*a23);
  a16=(a16+a15);
  if (res[1]!=0) res[1][3]=a16;
  a16=(a12/a01);
  a20=(a16*a20);
  a21=(a21/a01);
  a20=(a20-a21);
  a20=(a11*a20);
  a23=(a12*a23);
  a20=(a20+a23);
  if (res[1]!=0) res[1][4]=a20;
  a20=1.8196779242861130e-01;
  a23=2.5000000000000000e-01;
  a19=(a01*a19);
  a21=(a14*a19);
  a21=(a23*a21);
  a15=arg[1]? arg[1][7] : 0;
  a15=(a21+a15);
  a24=arg[1]? arg[1][8] : 0;
  a21=(a21+a24);
  a24=(a15+a21);
  a24=(a13*a24);
  a24=(a20*a24);
  a19=(a18*a19);
  a24=(a24-a19);
  if (res[1]!=0) res[1][5]=a24;
  a24=5.2155411096895330e+00;
  a21=(a21-a15);
  a21=(a17*a21);
  a21=(a24*a21);
  if (res[1]!=0) res[1][6]=a21;
  a21=0.;
  if (res[1]!=0) res[1][7]=a21;
  if (res[1]!=0) res[1][8]=a21;
  a15=arg[1]? arg[1][14] : 0;
  a19=(a04*a15);
  a25=arg[1]? arg[1][12] : 0;
  a26=(a00*a25);
  a27=(a03*a26);
  a28=arg[1]? arg[1][13] : 0;
  a29=(a02*a28);
  a29=(a01*a29);
  a27=(a27+a29);
  a27=(a05*a27);
  a19=(a19-a27);
  if (res[1]!=0) res[1][9]=a19;
  a28=(a03*a28);
  a28=(a01*a28);
  a19=(a02*a26);
  a28=(a28-a19);
  a28=(a05*a28);
  a15=(a06*a15);
  a28=(a28+a15);
  if (res[1]!=0) res[1][10]=a28;
  a28=(a25/a22);
  a28=(a09*a28);
  a15=arg[1]? arg[1][11] : 0;
  a19=(a08*a15);
  a27=(a07*a19);
  a28=(a28-a27);
  a28=(a11*a28);
  a27=arg[1]? arg[1][15] : 0;
  a29=(a10*a27);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][11]=a28;
  a15=(a09*a15);
  a15=(a11*a15);
  a28=(a08*a27);
  a15=(a15+a28);
  if (res[1]!=0) res[1][12]=a15;
  a26=(a16*a26);
  a19=(a19/a01);
  a26=(a26-a19);
  a26=(a11*a26);
  a27=(a12*a27);
  a26=(a26+a27);
  if (res[1]!=0) res[1][13]=a26;
  a25=(a01*a25);
  a26=(a14*a25);
  a26=(a23*a26);
  a27=arg[1]? arg[1][16] : 0;
  a27=(a26+a27);
  a19=arg[1]? arg[1][17] : 0;
  a26=(a26+a19);
  a19=(a27+a26);
  a19=(a13*a19);
  a19=(a20*a19);
  a25=(a18*a25);
  a19=(a19-a25);
  if (res[1]!=0) res[1][14]=a19;
  a26=(a26-a27);
  a26=(a17*a26);
  a26=(a24*a26);
  if (res[1]!=0) res[1][15]=a26;
  if (res[1]!=0) res[1][16]=a21;
  if (res[1]!=0) res[1][17]=a21;
  a26=arg[1]? arg[1][23] : 0;
  a27=(a04*a26);
  a19=arg[1]? arg[1][21] : 0;
  a25=(a00*a19);
  a15=(a03*a25);
  a28=arg[1]? arg[1][22] : 0;
  a29=(a02*a28);
  a29=(a01*a29);
  a15=(a15+a29);
  a15=(a05*a15);
  a27=(a27-a15);
  if (res[1]!=0) res[1][18]=a27;
  a28=(a03*a28);
  a28=(a01*a28);
  a27=(a02*a25);
  a28=(a28-a27);
  a28=(a05*a28);
  a26=(a06*a26);
  a28=(a28+a26);
  if (res[1]!=0) res[1][19]=a28;
  a28=(a19/a22);
  a28=(a09*a28);
  a26=arg[1]? arg[1][20] : 0;
  a27=(a08*a26);
  a15=(a07*a27);
  a28=(a28-a15);
  a28=(a11*a28);
  a15=arg[1]? arg[1][24] : 0;
  a29=(a10*a15);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][20]=a28;
  a26=(a09*a26);
  a26=(a11*a26);
  a28=(a08*a15);
  a26=(a26+a28);
  if (res[1]!=0) res[1][21]=a26;
  a25=(a16*a25);
  a27=(a27/a01);
  a25=(a25-a27);
  a25=(a11*a25);
  a15=(a12*a15);
  a25=(a25+a15);
  if (res[1]!=0) res[1][22]=a25;
  a19=(a01*a19);
  a25=(a14*a19);
  a25=(a23*a25);
  a15=arg[1]? arg[1][25] : 0;
  a15=(a25+a15);
  a27=arg[1]? arg[1][26] : 0;
  a25=(a25+a27);
  a27=(a15+a25);
  a27=(a13*a27);
  a27=(a20*a27);
  a19=(a18*a19);
  a27=(a27-a19);
  if (res[1]!=0) res[1][23]=a27;
  a25=(a25-a15);
  a25=(a17*a25);
  a25=(a24*a25);
  if (res[1]!=0) res[1][24]=a25;
  if (res[1]!=0) res[1][25]=a21;
  if (res[1]!=0) res[1][26]=a21;
  a25=arg[1]? arg[1][32] : 0;
  a15=(a04*a25);
  a27=arg[1]? arg[1][30] : 0;
  a19=(a00*a27);
  a26=(a03*a19);
  a28=arg[1]? arg[1][31] : 0;
  a29=(a02*a28);
  a29=(a01*a29);
  a26=(a26+a29);
  a26=(a05*a26);
  a15=(a15-a26);
  if (res[1]!=0) res[1][27]=a15;
  a28=(a03*a28);
  a28=(a01*a28);
  a15=(a02*a19);
  a28=(a28-a15);
  a28=(a05*a28);
  a25=(a06*a25);
  a28=(a28+a25);
  if (res[1]!=0) res[1][28]=a28;
  a28=(a27/a22);
  a28=(a09*a28);
  a25=arg[1]? arg[1][29] : 0;
  a15=(a08*a25);
  a26=(a07*a15);
  a28=(a28-a26);
  a28=(a11*a28);
  a26=arg[1]? arg[1][33] : 0;
  a29=(a10*a26);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][29]=a28;
  a25=(a09*a25);
  a25=(a11*a25);
  a28=(a08*a26);
  a25=(a25+a28);
  if (res[1]!=0) res[1][30]=a25;
  a19=(a16*a19);
  a15=(a15/a01);
  a19=(a19-a15);
  a19=(a11*a19);
  a26=(a12*a26);
  a19=(a19+a26);
  if (res[1]!=0) res[1][31]=a19;
  a27=(a01*a27);
  a19=(a14*a27);
  a19=(a23*a19);
  a26=arg[1]? arg[1][34] : 0;
  a26=(a19+a26);
  a15=arg[1]? arg[1][35] : 0;
  a19=(a19+a15);
  a15=(a26+a19);
  a15=(a13*a15);
  a15=(a20*a15);
  a27=(a18*a27);
  a15=(a15-a27);
  if (res[1]!=0) res[1][32]=a15;
  a19=(a19-a26);
  a19=(a17*a19);
  a19=(a24*a19);
  if (res[1]!=0) res[1][33]=a19;
  if (res[1]!=0) res[1][34]=a21;
  if (res[1]!=0) res[1][35]=a21;
  a19=arg[1]? arg[1][41] : 0;
  a26=(a04*a19);
  a15=arg[1]? arg[1][39] : 0;
  a27=(a00*a15);
  a25=(a03*a27);
  a28=arg[1]? arg[1][40] : 0;
  a29=(a02*a28);
  a29=(a01*a29);
  a25=(a25+a29);
  a25=(a05*a25);
  a26=(a26-a25);
  if (res[1]!=0) res[1][36]=a26;
  a28=(a03*a28);
  a28=(a01*a28);
  a26=(a02*a27);
  a28=(a28-a26);
  a28=(a05*a28);
  a19=(a06*a19);
  a28=(a28+a19);
  if (res[1]!=0) res[1][37]=a28;
  a28=(a15/a22);
  a28=(a09*a28);
  a19=arg[1]? arg[1][38] : 0;
  a26=(a08*a19);
  a25=(a07*a26);
  a28=(a28-a25);
  a28=(a11*a28);
  a25=arg[1]? arg[1][42] : 0;
  a29=(a10*a25);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][38]=a28;
  a19=(a09*a19);
  a19=(a11*a19);
  a28=(a08*a25);
  a19=(a19+a28);
  if (res[1]!=0) res[1][39]=a19;
  a27=(a16*a27);
  a26=(a26/a01);
  a27=(a27-a26);
  a27=(a11*a27);
  a25=(a12*a25);
  a27=(a27+a25);
  if (res[1]!=0) res[1][40]=a27;
  a15=(a01*a15);
  a27=(a14*a15);
  a27=(a23*a27);
  a25=arg[1]? arg[1][43] : 0;
  a25=(a27+a25);
  a26=arg[1]? arg[1][44] : 0;
  a27=(a27+a26);
  a26=(a25+a27);
  a26=(a13*a26);
  a26=(a20*a26);
  a15=(a18*a15);
  a26=(a26-a15);
  if (res[1]!=0) res[1][41]=a26;
  a27=(a27-a25);
  a27=(a17*a27);
  a27=(a24*a27);
  if (res[1]!=0) res[1][42]=a27;
  if (res[1]!=0) res[1][43]=a21;
  if (res[1]!=0) res[1][44]=a21;
  a27=arg[1]? arg[1][50] : 0;
  a25=(a04*a27);
  a26=arg[1]? arg[1][48] : 0;
  a15=(a00*a26);
  a19=(a03*a15);
  a28=arg[1]? arg[1][49] : 0;
  a29=(a02*a28);
  a29=(a01*a29);
  a19=(a19+a29);
  a19=(a05*a19);
  a25=(a25-a19);
  if (res[1]!=0) res[1][45]=a25;
  a28=(a03*a28);
  a28=(a01*a28);
  a25=(a02*a15);
  a28=(a28-a25);
  a28=(a05*a28);
  a27=(a06*a27);
  a28=(a28+a27);
  if (res[1]!=0) res[1][46]=a28;
  a28=(a26/a22);
  a28=(a09*a28);
  a27=arg[1]? arg[1][47] : 0;
  a25=(a08*a27);
  a19=(a07*a25);
  a28=(a28-a19);
  a28=(a11*a28);
  a19=arg[1]? arg[1][51] : 0;
  a29=(a10*a19);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][47]=a28;
  a27=(a09*a27);
  a27=(a11*a27);
  a28=(a08*a19);
  a27=(a27+a28);
  if (res[1]!=0) res[1][48]=a27;
  a15=(a16*a15);
  a25=(a25/a01);
  a15=(a15-a25);
  a15=(a11*a15);
  a19=(a12*a19);
  a15=(a15+a19);
  if (res[1]!=0) res[1][49]=a15;
  a26=(a01*a26);
  a15=(a14*a26);
  a15=(a23*a15);
  a19=arg[1]? arg[1][52] : 0;
  a19=(a15+a19);
  a25=arg[1]? arg[1][53] : 0;
  a15=(a15+a25);
  a25=(a19+a15);
  a25=(a13*a25);
  a25=(a20*a25);
  a26=(a18*a26);
  a25=(a25-a26);
  if (res[1]!=0) res[1][50]=a25;
  a15=(a15-a19);
  a15=(a17*a15);
  a15=(a24*a15);
  if (res[1]!=0) res[1][51]=a15;
  if (res[1]!=0) res[1][52]=a21;
  if (res[1]!=0) res[1][53]=a21;
  a15=arg[1]? arg[1][59] : 0;
  a19=(a04*a15);
  a25=arg[1]? arg[1][57] : 0;
  a26=(a00*a25);
  a27=(a03*a26);
  a28=arg[1]? arg[1][58] : 0;
  a29=(a02*a28);
  a29=(a01*a29);
  a27=(a27+a29);
  a27=(a05*a27);
  a19=(a19-a27);
  if (res[1]!=0) res[1][54]=a19;
  a28=(a03*a28);
  a28=(a01*a28);
  a19=(a02*a26);
  a28=(a28-a19);
  a28=(a05*a28);
  a15=(a06*a15);
  a28=(a28+a15);
  if (res[1]!=0) res[1][55]=a28;
  a28=(a25/a22);
  a28=(a09*a28);
  a15=arg[1]? arg[1][56] : 0;
  a19=(a08*a15);
  a27=(a07*a19);
  a28=(a28-a27);
  a28=(a11*a28);
  a27=arg[1]? arg[1][60] : 0;
  a29=(a10*a27);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][56]=a28;
  a15=(a09*a15);
  a15=(a11*a15);
  a28=(a08*a27);
  a15=(a15+a28);
  if (res[1]!=0) res[1][57]=a15;
  a26=(a16*a26);
  a19=(a19/a01);
  a26=(a26-a19);
  a26=(a11*a26);
  a27=(a12*a27);
  a26=(a26+a27);
  if (res[1]!=0) res[1][58]=a26;
  a25=(a01*a25);
  a26=(a14*a25);
  a26=(a23*a26);
  a27=arg[1]? arg[1][61] : 0;
  a27=(a26+a27);
  a19=arg[1]? arg[1][62] : 0;
  a26=(a26+a19);
  a19=(a27+a26);
  a19=(a13*a19);
  a19=(a20*a19);
  a25=(a18*a25);
  a19=(a19-a25);
  if (res[1]!=0) res[1][59]=a19;
  a26=(a26-a27);
  a26=(a17*a26);
  a26=(a24*a26);
  if (res[1]!=0) res[1][60]=a26;
  if (res[1]!=0) res[1][61]=a21;
  if (res[1]!=0) res[1][62]=a21;
  a26=arg[1]? arg[1][68] : 0;
  a27=(a04*a26);
  a19=arg[1]? arg[1][66] : 0;
  a25=(a00*a19);
  a15=(a03*a25);
  a28=arg[1]? arg[1][67] : 0;
  a29=(a02*a28);
  a29=(a01*a29);
  a15=(a15+a29);
  a15=(a05*a15);
  a27=(a27-a15);
  if (res[1]!=0) res[1][63]=a27;
  a28=(a03*a28);
  a28=(a01*a28);
  a27=(a02*a25);
  a28=(a28-a27);
  a28=(a05*a28);
  a26=(a06*a26);
  a28=(a28+a26);
  if (res[1]!=0) res[1][64]=a28;
  a28=(a19/a22);
  a28=(a09*a28);
  a26=arg[1]? arg[1][65] : 0;
  a27=(a08*a26);
  a15=(a07*a27);
  a28=(a28-a15);
  a28=(a11*a28);
  a15=arg[1]? arg[1][69] : 0;
  a29=(a10*a15);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][65]=a28;
  a26=(a09*a26);
  a26=(a11*a26);
  a28=(a08*a15);
  a26=(a26+a28);
  if (res[1]!=0) res[1][66]=a26;
  a25=(a16*a25);
  a27=(a27/a01);
  a25=(a25-a27);
  a25=(a11*a25);
  a15=(a12*a15);
  a25=(a25+a15);
  if (res[1]!=0) res[1][67]=a25;
  a19=(a01*a19);
  a25=(a14*a19);
  a25=(a23*a25);
  a15=arg[1]? arg[1][70] : 0;
  a15=(a25+a15);
  a27=arg[1]? arg[1][71] : 0;
  a25=(a25+a27);
  a27=(a15+a25);
  a27=(a13*a27);
  a27=(a20*a27);
  a19=(a18*a19);
  a27=(a27-a19);
  if (res[1]!=0) res[1][68]=a27;
  a25=(a25-a15);
  a25=(a17*a25);
  a25=(a24*a25);
  if (res[1]!=0) res[1][69]=a25;
  if (res[1]!=0) res[1][70]=a21;
  if (res[1]!=0) res[1][71]=a21;
  a25=arg[1]? arg[1][77] : 0;
  a15=(a04*a25);
  a27=arg[1]? arg[1][75] : 0;
  a19=(a00*a27);
  a26=(a03*a19);
  a28=arg[1]? arg[1][76] : 0;
  a29=(a02*a28);
  a29=(a01*a29);
  a26=(a26+a29);
  a26=(a05*a26);
  a15=(a15-a26);
  if (res[1]!=0) res[1][72]=a15;
  a28=(a03*a28);
  a28=(a01*a28);
  a15=(a02*a19);
  a28=(a28-a15);
  a28=(a05*a28);
  a25=(a06*a25);
  a28=(a28+a25);
  if (res[1]!=0) res[1][73]=a28;
  a28=(a27/a22);
  a28=(a09*a28);
  a25=arg[1]? arg[1][74] : 0;
  a15=(a08*a25);
  a26=(a07*a15);
  a28=(a28-a26);
  a28=(a11*a28);
  a26=arg[1]? arg[1][78] : 0;
  a29=(a10*a26);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][74]=a28;
  a25=(a09*a25);
  a25=(a11*a25);
  a28=(a08*a26);
  a25=(a25+a28);
  if (res[1]!=0) res[1][75]=a25;
  a19=(a16*a19);
  a15=(a15/a01);
  a19=(a19-a15);
  a19=(a11*a19);
  a26=(a12*a26);
  a19=(a19+a26);
  if (res[1]!=0) res[1][76]=a19;
  a27=(a01*a27);
  a19=(a14*a27);
  a19=(a23*a19);
  a26=arg[1]? arg[1][79] : 0;
  a26=(a19+a26);
  a15=arg[1]? arg[1][80] : 0;
  a19=(a19+a15);
  a15=(a26+a19);
  a15=(a13*a15);
  a15=(a20*a15);
  a27=(a18*a27);
  a15=(a15-a27);
  if (res[1]!=0) res[1][77]=a15;
  a19=(a19-a26);
  a19=(a17*a19);
  a19=(a24*a19);
  if (res[1]!=0) res[1][78]=a19;
  if (res[1]!=0) res[1][79]=a21;
  if (res[1]!=0) res[1][80]=a21;
  a19=arg[2]? arg[2][5] : 0;
  a26=(a04*a19);
  a15=arg[2]? arg[2][3] : 0;
  a27=(a00*a15);
  a25=(a03*a27);
  a28=arg[2]? arg[2][4] : 0;
  a29=(a02*a28);
  a29=(a01*a29);
  a25=(a25+a29);
  a25=(a05*a25);
  a26=(a26-a25);
  if (res[2]!=0) res[2][0]=a26;
  a28=(a03*a28);
  a28=(a01*a28);
  a26=(a02*a27);
  a28=(a28-a26);
  a28=(a05*a28);
  a19=(a06*a19);
  a28=(a28+a19);
  if (res[2]!=0) res[2][1]=a28;
  a28=(a15/a22);
  a28=(a09*a28);
  a19=arg[2]? arg[2][2] : 0;
  a26=(a08*a19);
  a25=(a07*a26);
  a28=(a28-a25);
  a28=(a11*a28);
  a25=arg[2]? arg[2][6] : 0;
  a29=(a10*a25);
  a28=(a28+a29);
  a28=(-a28);
  if (res[2]!=0) res[2][2]=a28;
  a19=(a09*a19);
  a19=(a11*a19);
  a28=(a08*a25);
  a19=(a19+a28);
  if (res[2]!=0) res[2][3]=a19;
  a27=(a16*a27);
  a26=(a26/a01);
  a27=(a27-a26);
  a27=(a11*a27);
  a25=(a12*a25);
  a27=(a27+a25);
  if (res[2]!=0) res[2][4]=a27;
  a15=(a01*a15);
  a27=(a14*a15);
  a27=(a23*a27);
  a25=arg[2]? arg[2][7] : 0;
  a25=(a27+a25);
  a26=arg[2]? arg[2][8] : 0;
  a27=(a27+a26);
  a26=(a25+a27);
  a26=(a13*a26);
  a26=(a20*a26);
  a15=(a18*a15);
  a26=(a26-a15);
  if (res[2]!=0) res[2][5]=a26;
  a27=(a27-a25);
  a27=(a17*a27);
  a27=(a24*a27);
  if (res[2]!=0) res[2][6]=a27;
  a27=1.;
  if (res[2]!=0) res[2][7]=a27;
  if (res[2]!=0) res[2][8]=a21;
  a25=arg[2]? arg[2][14] : 0;
  a04=(a04*a25);
  a26=arg[2]? arg[2][12] : 0;
  a00=(a00*a26);
  a15=(a03*a00);
  a19=arg[2]? arg[2][13] : 0;
  a28=(a02*a19);
  a28=(a01*a28);
  a15=(a15+a28);
  a15=(a05*a15);
  a04=(a04-a15);
  if (res[2]!=0) res[2][9]=a04;
  a03=(a03*a19);
  a03=(a01*a03);
  a02=(a02*a00);
  a03=(a03-a02);
  a05=(a05*a03);
  a06=(a06*a25);
  a05=(a05+a06);
  if (res[2]!=0) res[2][10]=a05;
  a22=(a26/a22);
  a22=(a09*a22);
  a05=arg[2]? arg[2][11] : 0;
  a06=(a08*a05);
  a07=(a07*a06);
  a22=(a22-a07);
  a22=(a11*a22);
  a07=arg[2]? arg[2][15] : 0;
  a10=(a10*a07);
  a22=(a22+a10);
  a22=(-a22);
  if (res[2]!=0) res[2][11]=a22;
  a09=(a09*a05);
  a09=(a11*a09);
  a08=(a08*a07);
  a09=(a09+a08);
  if (res[2]!=0) res[2][12]=a09;
  a16=(a16*a00);
  a06=(a06/a01);
  a16=(a16-a06);
  a11=(a11*a16);
  a12=(a12*a07);
  a11=(a11+a12);
  if (res[2]!=0) res[2][13]=a11;
  a01=(a01*a26);
  a14=(a14*a01);
  a23=(a23*a14);
  a14=arg[2]? arg[2][16] : 0;
  a14=(a23+a14);
  a26=arg[2]? arg[2][17] : 0;
  a23=(a23+a26);
  a26=(a14+a23);
  a13=(a13*a26);
  a20=(a20*a13);
  a18=(a18*a01);
  a20=(a20-a18);
  if (res[2]!=0) res[2][14]=a20;
  a23=(a23-a14);
  a17=(a17*a23);
  a24=(a24*a17);
  if (res[2]!=0) res[2][15]=a24;
  if (res[2]!=0) res[2][16]=a21;
  if (res[2]!=0) res[2][17]=a27;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dynamics_rates_path_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int dynamics_rates_path_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real dynamics_rates_path_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_rates_path_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_rates_path_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_rates_path_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_rates_path_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
