/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_rates_path_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {11, 1, 1};

/* dynamics_rates_path_expl_vde_adj:(i0[9],i1[9],i2[2],i3[2])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][6] : 0;
  a03=arg[1]? arg[1][3] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a00=sin(a00);
  a05=arg[1]? arg[1][4] : 0;
  a06=(a02*a05);
  a07=arg[0]? arg[0][3] : 0;
  a08=cos(a07);
  a09=(a06/a08);
  a09=(a00*a09);
  a04=(a04-a09);
  a09=tan(a07);
  a10=arg[1]? arg[1][2] : 0;
  a02=(a02*a10);
  a11=(a09*a02);
  a11=(a00*a11);
  a04=(a04+a11);
  if (res[0]!=0) res[0][2]=a04;
  a04=-5.3910639180000004e+01;
  a11=2.5000000000000000e-01;
  a12=4.4800000000000001e-01;
  a13=5.2155411096895330e+00;
  a14=arg[1]? arg[1][6] : 0;
  a13=(a13*a14);
  a12=(a12*a13);
  a13=2.;
  a14=1.8196779242861130e-01;
  a15=arg[1]? arg[1][5] : 0;
  a14=(a14*a15);
  a13=(a13*a14);
  a14=(a12+a13);
  a16=(a11*a14);
  a16=(a04*a16);
  a16=(a08*a16);
  a17=-9.8100000000000005e+00;
  a17=(a17*a15);
  a17=(a08*a17);
  a16=(a16-a17);
  a13=(a13-a12);
  a11=(a11*a13);
  a04=(a04*a11);
  a04=(a08*a04);
  a16=(a16+a04);
  a07=sin(a07);
  a04=(a01/a08);
  a11=(a04/a08);
  a11=(a11*a06);
  a11=(a07*a11);
  a16=(a16+a11);
  a02=(a01*a02);
  a11=casadi_sq(a08);
  a02=(a02/a11);
  a16=(a16-a02);
  a02=arg[0]? arg[0][4] : 0;
  a11=sin(a02);
  a06=arg[0]? arg[0][5] : 0;
  a12=arg[1]? arg[1][1] : 0;
  a17=(a06*a12);
  a15=(a11*a17);
  a15=(a07*a15);
  a16=(a16-a15);
  a02=cos(a02);
  a15=arg[1]? arg[1][0] : 0;
  a06=(a06*a15);
  a18=(a02*a06);
  a07=(a07*a18);
  a16=(a16-a07);
  if (res[0]!=0) res[0][3]=a16;
  a17=(a08*a17);
  a17=(a02*a17);
  a06=(a08*a06);
  a06=(a11*a06);
  a17=(a17-a06);
  if (res[0]!=0) res[0][4]=a17;
  a11=(a08*a11);
  a11=(a11*a12);
  a08=(a08*a02);
  a08=(a08*a15);
  a11=(a11+a08);
  if (res[0]!=0) res[0][5]=a11;
  a04=(a04*a05);
  a00=(a00*a03);
  a04=(a04+a00);
  a09=(a09*a01);
  a09=(a09*a10);
  a04=(a04-a09);
  if (res[0]!=0) res[0][6]=a04;
  if (res[0]!=0) res[0][7]=a13;
  if (res[0]!=0) res[0][8]=a14;
  a14=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][9]=a14;
  a14=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][10]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_rates_path_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dynamics_rates_path_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dynamics_rates_path_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dynamics_rates_path_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_rates_path_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_rates_path_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_rates_path_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_rates_path_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_rates_path_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
