/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[21] = {8, 2, 0, 8, 16, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};

/* dynamics_expl_vde_forw:(i0[8],i1[8x8],i2[8x2],i3[2],i4[4])->(o0[8],o1[8x8],o2[8x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][0] : 0;
  a1=2.7399999999999999e+01;
  a2=-9.8100000000000005e+00;
  a3=arg[4]? arg[4][1] : 0;
  a3=sin(a3);
  a2=(a2*a3);
  a2=(a1*a2);
  a0=(a0+a2);
  a0=(a0/a1);
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[0]? arg[0][2] : 0;
  a3=(a1*a2);
  a4=arg[0]? arg[0][5] : 0;
  a5=arg[0]? arg[0][1] : 0;
  a6=(a4*a5);
  a3=(a3-a6);
  a0=(a0-a3);
  if (res[0]!=0) res[0][0]=a0;
  a3=arg[0]? arg[0][0] : 0;
  a6=(a4*a3);
  a7=arg[0]? arg[0][3] : 0;
  a8=(a7*a2);
  a6=(a6-a8);
  a6=(-a6);
  if (res[0]!=0) res[0][1]=a6;
  a6=(a7*a5);
  a8=(a1*a3);
  a6=(a6-a8);
  a6=(-a6);
  if (res[0]!=0) res[0][2]=a6;
  a6=8.6080632770563145e-02;
  a8=1.1700973610735778e+01;
  a9=(a8*a4);
  a10=(a1*a9);
  a11=1.1669791786280525e+01;
  a12=(a11*a1);
  a13=(a4*a12);
  a10=(a10-a13);
  a10=(a6*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][3]=a10;
  a10=8.5691331800421669e-02;
  a13=1.1617014975544746e+01;
  a14=(a13*a7);
  a15=(a4*a14);
  a16=(a7*a9);
  a15=(a15-a16);
  a15=(a10*a15);
  a15=(-a15);
  if (res[0]!=0) res[0][4]=a15;
  a15=8.5462973703529135e-02;
  a16=arg[3]? arg[3][1] : 0;
  a17=(a7*a12);
  a18=(a1*a14);
  a17=(a17-a18);
  a16=(a16-a17);
  a16=(a15*a16);
  if (res[0]!=0) res[0][5]=a16;
  a17=1.1100000000000000e-01;
  a0=(a0/a17);
  a17=4.9700000000000000e-01;
  a16=(a17*a16);
  a18=2.2200000000000000e-01;
  a16=(a16/a18);
  a18=(a0-a16);
  if (res[0]!=0) res[0][6]=a18;
  a0=(a0+a16);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a16=(a2*a0);
  a18=arg[1]? arg[1][2] : 0;
  a19=(a1*a18);
  a16=(a16+a19);
  a19=arg[1]? arg[1][5] : 0;
  a20=(a5*a19);
  a21=arg[1]? arg[1][1] : 0;
  a22=(a4*a21);
  a20=(a20+a22);
  a16=(a16-a20);
  a20=(-a16);
  if (res[1]!=0) res[1][0]=a20;
  a20=(a3*a19);
  a22=arg[1]? arg[1][0] : 0;
  a23=(a4*a22);
  a20=(a20+a23);
  a23=arg[1]? arg[1][3] : 0;
  a24=(a2*a23);
  a18=(a7*a18);
  a24=(a24+a18);
  a20=(a20-a24);
  a20=(-a20);
  if (res[1]!=0) res[1][1]=a20;
  a20=(a5*a23);
  a21=(a7*a21);
  a20=(a20+a21);
  a21=(a3*a0);
  a22=(a1*a22);
  a21=(a21+a22);
  a20=(a20-a21);
  a20=(-a20);
  if (res[1]!=0) res[1][2]=a20;
  a20=(a9*a0);
  a21=(a8*a19);
  a22=(a1*a21);
  a20=(a20+a22);
  a22=(a12*a19);
  a24=(a11*a0);
  a18=(a4*a24);
  a22=(a22+a18);
  a20=(a20-a22);
  a20=(a6*a20);
  a20=(-a20);
  if (res[1]!=0) res[1][3]=a20;
  a19=(a14*a19);
  a20=(a13*a23);
  a22=(a4*a20);
  a19=(a19+a22);
  a22=(a9*a23);
  a21=(a7*a21);
  a22=(a22+a21);
  a19=(a19-a22);
  a19=(a10*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][4]=a19;
  a23=(a12*a23);
  a24=(a7*a24);
  a23=(a23+a24);
  a0=(a14*a0);
  a20=(a1*a20);
  a0=(a0+a20);
  a23=(a23-a0);
  a23=(a15*a23);
  a0=(-a23);
  if (res[1]!=0) res[1][5]=a0;
  a0=4.5045045045045047e+00;
  a23=(a17*a23);
  a23=(a0*a23);
  a20=9.0090090090090094e+00;
  a16=(a20*a16);
  a24=(a23-a16);
  if (res[1]!=0) res[1][6]=a24;
  a16=(a16+a23);
  a16=(-a16);
  if (res[1]!=0) res[1][7]=a16;
  a16=arg[1]? arg[1][12] : 0;
  a23=(a2*a16);
  a24=arg[1]? arg[1][10] : 0;
  a19=(a1*a24);
  a23=(a23+a19);
  a19=arg[1]? arg[1][13] : 0;
  a22=(a5*a19);
  a21=arg[1]? arg[1][9] : 0;
  a18=(a4*a21);
  a22=(a22+a18);
  a23=(a23-a22);
  a22=(-a23);
  if (res[1]!=0) res[1][8]=a22;
  a22=(a3*a19);
  a18=arg[1]? arg[1][8] : 0;
  a25=(a4*a18);
  a22=(a22+a25);
  a25=arg[1]? arg[1][11] : 0;
  a26=(a2*a25);
  a24=(a7*a24);
  a26=(a26+a24);
  a22=(a22-a26);
  a22=(-a22);
  if (res[1]!=0) res[1][9]=a22;
  a22=(a5*a25);
  a21=(a7*a21);
  a22=(a22+a21);
  a21=(a3*a16);
  a18=(a1*a18);
  a21=(a21+a18);
  a22=(a22-a21);
  a22=(-a22);
  if (res[1]!=0) res[1][10]=a22;
  a22=(a9*a16);
  a21=(a8*a19);
  a18=(a1*a21);
  a22=(a22+a18);
  a18=(a12*a19);
  a26=(a11*a16);
  a24=(a4*a26);
  a18=(a18+a24);
  a22=(a22-a18);
  a22=(a6*a22);
  a22=(-a22);
  if (res[1]!=0) res[1][11]=a22;
  a19=(a14*a19);
  a22=(a13*a25);
  a18=(a4*a22);
  a19=(a19+a18);
  a18=(a9*a25);
  a21=(a7*a21);
  a18=(a18+a21);
  a19=(a19-a18);
  a19=(a10*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][12]=a19;
  a25=(a12*a25);
  a26=(a7*a26);
  a25=(a25+a26);
  a16=(a14*a16);
  a22=(a1*a22);
  a16=(a16+a22);
  a25=(a25-a16);
  a25=(a15*a25);
  a16=(-a25);
  if (res[1]!=0) res[1][13]=a16;
  a25=(a17*a25);
  a25=(a0*a25);
  a23=(a20*a23);
  a16=(a25-a23);
  if (res[1]!=0) res[1][14]=a16;
  a23=(a23+a25);
  a23=(-a23);
  if (res[1]!=0) res[1][15]=a23;
  a23=arg[1]? arg[1][20] : 0;
  a25=(a2*a23);
  a16=arg[1]? arg[1][18] : 0;
  a22=(a1*a16);
  a25=(a25+a22);
  a22=arg[1]? arg[1][21] : 0;
  a26=(a5*a22);
  a19=arg[1]? arg[1][17] : 0;
  a18=(a4*a19);
  a26=(a26+a18);
  a25=(a25-a26);
  a26=(-a25);
  if (res[1]!=0) res[1][16]=a26;
  a26=(a3*a22);
  a18=arg[1]? arg[1][16] : 0;
  a21=(a4*a18);
  a26=(a26+a21);
  a21=arg[1]? arg[1][19] : 0;
  a24=(a2*a21);
  a16=(a7*a16);
  a24=(a24+a16);
  a26=(a26-a24);
  a26=(-a26);
  if (res[1]!=0) res[1][17]=a26;
  a26=(a5*a21);
  a19=(a7*a19);
  a26=(a26+a19);
  a19=(a3*a23);
  a18=(a1*a18);
  a19=(a19+a18);
  a26=(a26-a19);
  a26=(-a26);
  if (res[1]!=0) res[1][18]=a26;
  a26=(a9*a23);
  a19=(a8*a22);
  a18=(a1*a19);
  a26=(a26+a18);
  a18=(a12*a22);
  a24=(a11*a23);
  a16=(a4*a24);
  a18=(a18+a16);
  a26=(a26-a18);
  a26=(a6*a26);
  a26=(-a26);
  if (res[1]!=0) res[1][19]=a26;
  a22=(a14*a22);
  a26=(a13*a21);
  a18=(a4*a26);
  a22=(a22+a18);
  a18=(a9*a21);
  a19=(a7*a19);
  a18=(a18+a19);
  a22=(a22-a18);
  a22=(a10*a22);
  a22=(-a22);
  if (res[1]!=0) res[1][20]=a22;
  a21=(a12*a21);
  a24=(a7*a24);
  a21=(a21+a24);
  a23=(a14*a23);
  a26=(a1*a26);
  a23=(a23+a26);
  a21=(a21-a23);
  a21=(a15*a21);
  a23=(-a21);
  if (res[1]!=0) res[1][21]=a23;
  a21=(a17*a21);
  a21=(a0*a21);
  a25=(a20*a25);
  a23=(a21-a25);
  if (res[1]!=0) res[1][22]=a23;
  a25=(a25+a21);
  a25=(-a25);
  if (res[1]!=0) res[1][23]=a25;
  a25=arg[1]? arg[1][28] : 0;
  a21=(a2*a25);
  a23=arg[1]? arg[1][26] : 0;
  a26=(a1*a23);
  a21=(a21+a26);
  a26=arg[1]? arg[1][29] : 0;
  a24=(a5*a26);
  a22=arg[1]? arg[1][25] : 0;
  a18=(a4*a22);
  a24=(a24+a18);
  a21=(a21-a24);
  a24=(-a21);
  if (res[1]!=0) res[1][24]=a24;
  a24=(a3*a26);
  a18=arg[1]? arg[1][24] : 0;
  a19=(a4*a18);
  a24=(a24+a19);
  a19=arg[1]? arg[1][27] : 0;
  a16=(a2*a19);
  a23=(a7*a23);
  a16=(a16+a23);
  a24=(a24-a16);
  a24=(-a24);
  if (res[1]!=0) res[1][25]=a24;
  a24=(a5*a19);
  a22=(a7*a22);
  a24=(a24+a22);
  a22=(a3*a25);
  a18=(a1*a18);
  a22=(a22+a18);
  a24=(a24-a22);
  a24=(-a24);
  if (res[1]!=0) res[1][26]=a24;
  a24=(a9*a25);
  a22=(a8*a26);
  a18=(a1*a22);
  a24=(a24+a18);
  a18=(a12*a26);
  a16=(a11*a25);
  a23=(a4*a16);
  a18=(a18+a23);
  a24=(a24-a18);
  a24=(a6*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][27]=a24;
  a26=(a14*a26);
  a24=(a13*a19);
  a18=(a4*a24);
  a26=(a26+a18);
  a18=(a9*a19);
  a22=(a7*a22);
  a18=(a18+a22);
  a26=(a26-a18);
  a26=(a10*a26);
  a26=(-a26);
  if (res[1]!=0) res[1][28]=a26;
  a19=(a12*a19);
  a16=(a7*a16);
  a19=(a19+a16);
  a25=(a14*a25);
  a24=(a1*a24);
  a25=(a25+a24);
  a19=(a19-a25);
  a19=(a15*a19);
  a25=(-a19);
  if (res[1]!=0) res[1][29]=a25;
  a19=(a17*a19);
  a19=(a0*a19);
  a21=(a20*a21);
  a25=(a19-a21);
  if (res[1]!=0) res[1][30]=a25;
  a21=(a21+a19);
  a21=(-a21);
  if (res[1]!=0) res[1][31]=a21;
  a21=arg[1]? arg[1][36] : 0;
  a19=(a2*a21);
  a25=arg[1]? arg[1][34] : 0;
  a24=(a1*a25);
  a19=(a19+a24);
  a24=arg[1]? arg[1][37] : 0;
  a16=(a5*a24);
  a26=arg[1]? arg[1][33] : 0;
  a18=(a4*a26);
  a16=(a16+a18);
  a19=(a19-a16);
  a16=(-a19);
  if (res[1]!=0) res[1][32]=a16;
  a16=(a3*a24);
  a18=arg[1]? arg[1][32] : 0;
  a22=(a4*a18);
  a16=(a16+a22);
  a22=arg[1]? arg[1][35] : 0;
  a23=(a2*a22);
  a25=(a7*a25);
  a23=(a23+a25);
  a16=(a16-a23);
  a16=(-a16);
  if (res[1]!=0) res[1][33]=a16;
  a16=(a5*a22);
  a26=(a7*a26);
  a16=(a16+a26);
  a26=(a3*a21);
  a18=(a1*a18);
  a26=(a26+a18);
  a16=(a16-a26);
  a16=(-a16);
  if (res[1]!=0) res[1][34]=a16;
  a16=(a9*a21);
  a26=(a8*a24);
  a18=(a1*a26);
  a16=(a16+a18);
  a18=(a12*a24);
  a23=(a11*a21);
  a25=(a4*a23);
  a18=(a18+a25);
  a16=(a16-a18);
  a16=(a6*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][35]=a16;
  a24=(a14*a24);
  a16=(a13*a22);
  a18=(a4*a16);
  a24=(a24+a18);
  a18=(a9*a22);
  a26=(a7*a26);
  a18=(a18+a26);
  a24=(a24-a18);
  a24=(a10*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][36]=a24;
  a22=(a12*a22);
  a23=(a7*a23);
  a22=(a22+a23);
  a21=(a14*a21);
  a16=(a1*a16);
  a21=(a21+a16);
  a22=(a22-a21);
  a22=(a15*a22);
  a21=(-a22);
  if (res[1]!=0) res[1][37]=a21;
  a22=(a17*a22);
  a22=(a0*a22);
  a19=(a20*a19);
  a21=(a22-a19);
  if (res[1]!=0) res[1][38]=a21;
  a19=(a19+a22);
  a19=(-a19);
  if (res[1]!=0) res[1][39]=a19;
  a19=arg[1]? arg[1][44] : 0;
  a22=(a2*a19);
  a21=arg[1]? arg[1][42] : 0;
  a16=(a1*a21);
  a22=(a22+a16);
  a16=arg[1]? arg[1][45] : 0;
  a23=(a5*a16);
  a24=arg[1]? arg[1][41] : 0;
  a18=(a4*a24);
  a23=(a23+a18);
  a22=(a22-a23);
  a23=(-a22);
  if (res[1]!=0) res[1][40]=a23;
  a23=(a3*a16);
  a18=arg[1]? arg[1][40] : 0;
  a26=(a4*a18);
  a23=(a23+a26);
  a26=arg[1]? arg[1][43] : 0;
  a25=(a2*a26);
  a21=(a7*a21);
  a25=(a25+a21);
  a23=(a23-a25);
  a23=(-a23);
  if (res[1]!=0) res[1][41]=a23;
  a23=(a5*a26);
  a24=(a7*a24);
  a23=(a23+a24);
  a24=(a3*a19);
  a18=(a1*a18);
  a24=(a24+a18);
  a23=(a23-a24);
  a23=(-a23);
  if (res[1]!=0) res[1][42]=a23;
  a23=(a9*a19);
  a24=(a8*a16);
  a18=(a1*a24);
  a23=(a23+a18);
  a18=(a12*a16);
  a25=(a11*a19);
  a21=(a4*a25);
  a18=(a18+a21);
  a23=(a23-a18);
  a23=(a6*a23);
  a23=(-a23);
  if (res[1]!=0) res[1][43]=a23;
  a16=(a14*a16);
  a23=(a13*a26);
  a18=(a4*a23);
  a16=(a16+a18);
  a18=(a9*a26);
  a24=(a7*a24);
  a18=(a18+a24);
  a16=(a16-a18);
  a16=(a10*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][44]=a16;
  a26=(a12*a26);
  a25=(a7*a25);
  a26=(a26+a25);
  a19=(a14*a19);
  a23=(a1*a23);
  a19=(a19+a23);
  a26=(a26-a19);
  a26=(a15*a26);
  a19=(-a26);
  if (res[1]!=0) res[1][45]=a19;
  a26=(a17*a26);
  a26=(a0*a26);
  a22=(a20*a22);
  a19=(a26-a22);
  if (res[1]!=0) res[1][46]=a19;
  a22=(a22+a26);
  a22=(-a22);
  if (res[1]!=0) res[1][47]=a22;
  a22=arg[1]? arg[1][52] : 0;
  a26=(a2*a22);
  a19=arg[1]? arg[1][50] : 0;
  a23=(a1*a19);
  a26=(a26+a23);
  a23=arg[1]? arg[1][53] : 0;
  a25=(a5*a23);
  a16=arg[1]? arg[1][49] : 0;
  a18=(a4*a16);
  a25=(a25+a18);
  a26=(a26-a25);
  a25=(-a26);
  if (res[1]!=0) res[1][48]=a25;
  a25=(a3*a23);
  a18=arg[1]? arg[1][48] : 0;
  a24=(a4*a18);
  a25=(a25+a24);
  a24=arg[1]? arg[1][51] : 0;
  a21=(a2*a24);
  a19=(a7*a19);
  a21=(a21+a19);
  a25=(a25-a21);
  a25=(-a25);
  if (res[1]!=0) res[1][49]=a25;
  a25=(a5*a24);
  a16=(a7*a16);
  a25=(a25+a16);
  a16=(a3*a22);
  a18=(a1*a18);
  a16=(a16+a18);
  a25=(a25-a16);
  a25=(-a25);
  if (res[1]!=0) res[1][50]=a25;
  a25=(a9*a22);
  a16=(a8*a23);
  a18=(a1*a16);
  a25=(a25+a18);
  a18=(a12*a23);
  a21=(a11*a22);
  a19=(a4*a21);
  a18=(a18+a19);
  a25=(a25-a18);
  a25=(a6*a25);
  a25=(-a25);
  if (res[1]!=0) res[1][51]=a25;
  a23=(a14*a23);
  a25=(a13*a24);
  a18=(a4*a25);
  a23=(a23+a18);
  a18=(a9*a24);
  a16=(a7*a16);
  a18=(a18+a16);
  a23=(a23-a18);
  a23=(a10*a23);
  a23=(-a23);
  if (res[1]!=0) res[1][52]=a23;
  a24=(a12*a24);
  a21=(a7*a21);
  a24=(a24+a21);
  a22=(a14*a22);
  a25=(a1*a25);
  a22=(a22+a25);
  a24=(a24-a22);
  a24=(a15*a24);
  a22=(-a24);
  if (res[1]!=0) res[1][53]=a22;
  a24=(a17*a24);
  a24=(a0*a24);
  a26=(a20*a26);
  a22=(a24-a26);
  if (res[1]!=0) res[1][54]=a22;
  a26=(a26+a24);
  a26=(-a26);
  if (res[1]!=0) res[1][55]=a26;
  a26=arg[1]? arg[1][60] : 0;
  a24=(a2*a26);
  a22=arg[1]? arg[1][58] : 0;
  a25=(a1*a22);
  a24=(a24+a25);
  a25=arg[1]? arg[1][61] : 0;
  a21=(a5*a25);
  a23=arg[1]? arg[1][57] : 0;
  a18=(a4*a23);
  a21=(a21+a18);
  a24=(a24-a21);
  a21=(-a24);
  if (res[1]!=0) res[1][56]=a21;
  a21=(a3*a25);
  a18=arg[1]? arg[1][56] : 0;
  a16=(a4*a18);
  a21=(a21+a16);
  a16=arg[1]? arg[1][59] : 0;
  a19=(a2*a16);
  a22=(a7*a22);
  a19=(a19+a22);
  a21=(a21-a19);
  a21=(-a21);
  if (res[1]!=0) res[1][57]=a21;
  a21=(a5*a16);
  a23=(a7*a23);
  a21=(a21+a23);
  a23=(a3*a26);
  a18=(a1*a18);
  a23=(a23+a18);
  a21=(a21-a23);
  a21=(-a21);
  if (res[1]!=0) res[1][58]=a21;
  a21=(a9*a26);
  a23=(a8*a25);
  a18=(a1*a23);
  a21=(a21+a18);
  a18=(a12*a25);
  a19=(a11*a26);
  a22=(a4*a19);
  a18=(a18+a22);
  a21=(a21-a18);
  a21=(a6*a21);
  a21=(-a21);
  if (res[1]!=0) res[1][59]=a21;
  a25=(a14*a25);
  a21=(a13*a16);
  a18=(a4*a21);
  a25=(a25+a18);
  a18=(a9*a16);
  a23=(a7*a23);
  a18=(a18+a23);
  a25=(a25-a18);
  a25=(a10*a25);
  a25=(-a25);
  if (res[1]!=0) res[1][60]=a25;
  a16=(a12*a16);
  a19=(a7*a19);
  a16=(a16+a19);
  a26=(a14*a26);
  a21=(a1*a21);
  a26=(a26+a21);
  a16=(a16-a26);
  a16=(a15*a16);
  a26=(-a16);
  if (res[1]!=0) res[1][61]=a26;
  a16=(a17*a16);
  a16=(a0*a16);
  a24=(a20*a24);
  a26=(a16-a24);
  if (res[1]!=0) res[1][62]=a26;
  a24=(a24+a16);
  a24=(-a24);
  if (res[1]!=0) res[1][63]=a24;
  a24=3.6496350364963508e-02;
  a16=arg[2]? arg[2][4] : 0;
  a26=(a2*a16);
  a21=arg[2]? arg[2][2] : 0;
  a19=(a1*a21);
  a26=(a26+a19);
  a19=arg[2]? arg[2][5] : 0;
  a25=(a5*a19);
  a18=arg[2]? arg[2][1] : 0;
  a23=(a4*a18);
  a25=(a25+a23);
  a26=(a26-a25);
  a24=(a24-a26);
  if (res[2]!=0) res[2][0]=a24;
  a24=(a3*a19);
  a25=arg[2]? arg[2][0] : 0;
  a23=(a4*a25);
  a24=(a24+a23);
  a23=arg[2]? arg[2][3] : 0;
  a22=(a2*a23);
  a21=(a7*a21);
  a22=(a22+a21);
  a24=(a24-a22);
  a24=(-a24);
  if (res[2]!=0) res[2][1]=a24;
  a24=(a5*a23);
  a18=(a7*a18);
  a24=(a24+a18);
  a18=(a3*a16);
  a25=(a1*a25);
  a18=(a18+a25);
  a24=(a24-a18);
  a24=(-a24);
  if (res[2]!=0) res[2][2]=a24;
  a24=(a9*a16);
  a18=(a8*a19);
  a25=(a1*a18);
  a24=(a24+a25);
  a25=(a12*a19);
  a22=(a11*a16);
  a21=(a4*a22);
  a25=(a25+a21);
  a24=(a24-a25);
  a24=(a6*a24);
  a24=(-a24);
  if (res[2]!=0) res[2][3]=a24;
  a19=(a14*a19);
  a24=(a13*a23);
  a25=(a4*a24);
  a19=(a19+a25);
  a25=(a9*a23);
  a18=(a7*a18);
  a25=(a25+a18);
  a19=(a19-a25);
  a19=(a10*a19);
  a19=(-a19);
  if (res[2]!=0) res[2][4]=a19;
  a23=(a12*a23);
  a22=(a7*a22);
  a23=(a23+a22);
  a16=(a14*a16);
  a24=(a1*a24);
  a16=(a16+a24);
  a23=(a23-a16);
  a23=(a15*a23);
  a16=(-a23);
  if (res[2]!=0) res[2][5]=a16;
  a16=3.2879594923390548e-01;
  a23=(a17*a23);
  a23=(a0*a23);
  a26=(a20*a26);
  a24=(a23-a26);
  a24=(a16+a24);
  if (res[2]!=0) res[2][6]=a24;
  a26=(a26+a23);
  a16=(a16-a26);
  if (res[2]!=0) res[2][7]=a16;
  a16=arg[2]? arg[2][12] : 0;
  a26=(a2*a16);
  a23=arg[2]? arg[2][10] : 0;
  a24=(a1*a23);
  a26=(a26+a24);
  a24=arg[2]? arg[2][13] : 0;
  a22=(a5*a24);
  a19=arg[2]? arg[2][9] : 0;
  a25=(a4*a19);
  a22=(a22+a25);
  a26=(a26-a22);
  a22=(-a26);
  if (res[2]!=0) res[2][8]=a22;
  a22=(a3*a24);
  a25=arg[2]? arg[2][8] : 0;
  a18=(a4*a25);
  a22=(a22+a18);
  a18=arg[2]? arg[2][11] : 0;
  a2=(a2*a18);
  a23=(a7*a23);
  a2=(a2+a23);
  a22=(a22-a2);
  a22=(-a22);
  if (res[2]!=0) res[2][9]=a22;
  a5=(a5*a18);
  a19=(a7*a19);
  a5=(a5+a19);
  a3=(a3*a16);
  a25=(a1*a25);
  a3=(a3+a25);
  a5=(a5-a3);
  a5=(-a5);
  if (res[2]!=0) res[2][10]=a5;
  a5=(a9*a16);
  a8=(a8*a24);
  a3=(a1*a8);
  a5=(a5+a3);
  a3=(a12*a24);
  a11=(a11*a16);
  a25=(a4*a11);
  a3=(a3+a25);
  a5=(a5-a3);
  a6=(a6*a5);
  a6=(-a6);
  if (res[2]!=0) res[2][11]=a6;
  a24=(a14*a24);
  a13=(a13*a18);
  a4=(a4*a13);
  a24=(a24+a4);
  a9=(a9*a18);
  a8=(a7*a8);
  a9=(a9+a8);
  a24=(a24-a9);
  a10=(a10*a24);
  a10=(-a10);
  if (res[2]!=0) res[2][12]=a10;
  a12=(a12*a18);
  a7=(a7*a11);
  a12=(a12+a7);
  a14=(a14*a16);
  a1=(a1*a13);
  a14=(a14+a1);
  a12=(a12-a14);
  a12=(a15*a12);
  a15=(a15-a12);
  if (res[2]!=0) res[2][13]=a15;
  a15=-1.9132926995790081e-01;
  a17=(a17*a12);
  a0=(a0*a17);
  a20=(a20*a26);
  a26=(a0-a20);
  a15=(a15+a26);
  if (res[2]!=0) res[2][14]=a15;
  a15=1.9132926995790081e-01;
  a20=(a20+a0);
  a15=(a15-a20);
  if (res[2]!=0) res[2][15]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dynamics_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dynamics_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dynamics_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dynamics_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int dynamics_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real dynamics_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
